<?php\n/**\n * Plugin Name: SUT寰俊灏忕▼搴?
 * Plugin URI: https://github.com/sutchan/SutWxApp\n * Description: 涓篧ordPress缃戠珯鎻愪緵寰俊灏忕▼搴忓鎺ュ姛鑳斤紝鏀寔鍐呭灞曠ず銆佺數鍟嗗姛鑳姐€佺敤鎴风鐞嗐€佹秷鎭帹閫佺瓑銆?
 * Version: 1.0.9\n * Author: SUT\n * Author URI: https://github.com/sutchan\n * License: GPL2\n * License URI: https://www.gnu.org/licenses/gpl-2.0.html\n * Text Domain: sut-wechat-mini\n * Domain Path: /languages\n *\n * SUT寰俊灏忕▼搴忔槸涓€涓负WordPress缃戠珯鎻愪緵寰俊灏忕▼搴忓鎺ュ姛鑳界殑鎻掍欢锛?
 * 鏀寔鍐呭灞曠ず銆佺數鍟嗗姛鑳姐€佺敤鎴风鐞嗐€佹秷鎭帹閫佺瓑鍔熻兘銆?
 *\n * @package SUT_WeChat_Mini\n */\n\n// 闃叉鐩存帴璁块棶\nif ( ! defined( 'ABSPATH' ) ) {\n    exit;\n}\n\n/**\n * 鎻掍欢鐗堟湰鍙?
 */\ndefine( 'SUT_WECHAT_MINI_VERSION', '1.0.9' );\n\n/**\n * 鎻掍欢鐩綍缁濆璺緞\n */\ndefine( 'SUT_WECHAT_MINI_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );\n\n/**\n * 鎻掍欢URL\n */\ndefine( 'SUT_WECHAT_MINI_PLUGIN_URL', plugin_dir_url( __FILE__ ) );\n\n/**\n * 鎻掍欢涓绘枃浠惰矾寰?
 */\ndefine( 'SUT_WECHAT_MINI_PLUGIN_FILE', __FILE__ );\n\n/**\n * 鎻掍欢鏍圭洰褰曞悕\n */\ndefine( 'SUT_WECHAT_MINI_PLUGIN_BASENAME', plugin_basename( __FILE__ ) );\n\n/**\n * 鍔犺浇宸ュ叿鍑芥暟\n */\nif ( ! class_exists( 'SUT_WeChat_Mini_Utils' ) ) {\n    require_once SUT_WECHAT_MINI_PLUGIN_DIR . 'includes/utils/class-sut-wechat-mini-utils.php';\n}\n\n/**\n * 鍔犺浇瀹夎绫?
 */\nif ( ! class_exists( 'SUT_WeChat_Mini_Install' ) ) {\n    require_once SUT_WECHAT_MINI_PLUGIN_DIR . 'includes/install.php';\n}\n\n/**\n * 鍔犺浇鍔犺浇鍣ㄧ被\n */\nif ( ! class_exists( 'SUT_WeChat_Mini_Loader' ) ) {\n    require_once SUT_WECHAT_MINI_PLUGIN_DIR . 'includes/class-sut-wechat-mini-loader.php';\n}\n\n/**\n * 鍒濆鍖栨彃浠?
 *\n * @return SUT_WeChat_Mini_Loader 鎻掍欢鍔犺浇鍣ㄥ疄渚?
 */\nfunction sut_wechat_mini_init() {\n    // 妫€鏌HP鐗堟湰\n    if ( version_compare( PHP_VERSION, '5.6.0', '<' ) ) {\n        add_action( 'admin_notices', 'sut_wechat_mini_php_version_notice' );\n        return;\n    }\n    \n    // 妫€鏌ordPress鐗堟湰\n    if ( version_compare( get_bloginfo( 'version' ), '4.7', '<' ) ) {\n        add_action( 'admin_notices', 'sut_wechat_mini_wp_version_notice' );\n        return;\n    }\n    \n    // 鍒濆鍖栧姞杞藉櫒\n    $loader = SUT_WeChat_Mini_Loader::get_instance();\n    \n    return $loader;\n}\n\n/**\n * 鏄剧ずPHP鐗堟湰涓嶅吋瀹归€氱煡\n */\nfunction sut_wechat_mini_php_version_notice() {\n    $notice = sprintf( \n        esc_html__( 'SUT寰俊灏忕▼搴忔彃浠堕渶瑕丳HP 5.6.0鎴栨洿楂樼増鏈墠鑳借繍琛屻€傚綋鍓嶆偍鐨凱HP鐗堟湰鏄?%s銆傝鍗囩骇鎮ㄧ殑PHP鐗堟湰銆?, 'sut-wechat-mini' ), \n        PHP_VERSION\n    );\n    \n    echo '<div class="notice notice-error"><p>' . esc_html( $notice ) . '</p></div>';\n}\n\n/**\n * 鏄剧ずWordPress鐗堟湰涓嶅吋瀹归€氱煡\n */\nfunction sut_wechat_mini_wp_version_notice() {\n    $notice = sprintf( \n        esc_html__( 'SUT寰俊灏忕▼搴忔彃浠堕渶瑕乄ordPress 4.7鎴栨洿楂樼増鏈墠鑳借繍琛屻€傚綋鍓嶆偍鐨刉ordPress鐗堟湰鏄?%s銆傝鍗囩骇鎮ㄧ殑WordPress鐗堟湰銆?, 'sut-wechat-mini' ), \n        get_bloginfo( 'version' )\n    );\n    \n    echo '<div class="notice notice-error"><p>' . esc_html( $notice ) . '</p></div>';\n}\n\n/**\n * 鏄剧ず鎻掍欢鏈厤缃€氱煡\n */\nfunction sut_wechat_mini_config_notice() {\n    if ( ! current_user_can( 'manage_options' ) ) {\n        return;\n    }\n    \n    $settings_url = admin_url( 'admin.php?page=sut-wechat-mini' );\n    $notice = sprintf( \n        esc_html__( 'SUT寰俊灏忕▼搴忔彃浠跺凡婵€娲伙紝浣嗗皻鏈厤缃€傝鍓嶅線 %s 瀹屾垚閰嶇疆銆?, 'sut-wechat-mini' ),\n        '<a href="' . esc_url( $settings_url ) . '">' . esc_html__( '璁剧疆椤甸潰', 'sut-wechat-mini' ) . '</a>'\n    );\n    \n    echo '<div class="notice notice-warning"><p>' . wp_kses_post( $notice ) . '</p></div>';\n}\n\n/**\n * 鎻掍欢婵€娲婚挬瀛?
 *\n * @param bool $network_wide 鏄惁鍦ㄧ綉缁滆寖鍥村唴婵€娲?
 */\nfunction sut_wechat_mini_activate( $network_wide ) {\n    // 鍒濆鍖栧畨瑁?
    SUT_WeChat_Mini_Install::activate( $network_wide );\n}\n\n/**\n * 鎻掍欢鍋滅敤閽╁瓙\n */\nfunction sut_wechat_mini_deactivate() {\n    // 鎵ц鍋滅敤鎿嶄綔\n    SUT_WeChat_Mini_Install::deactivate();\n}\n\n/**\n * 鎻掍欢鍗歌浇閽╁瓙\n */\nfunction sut_wechat_mini_uninstall() {\n    // 鎵ц鍗歌浇鎿嶄綔\n    SUT_WeChat_Mini_Install::uninstall();\n}\n\n// 娉ㄥ唽婵€娲汇€佸仠鐢ㄥ拰鍗歌浇閽╁瓙\nregister_activation_hook( __FILE__, 'sut_wechat_mini_activate' );\nregister_deactivation_hook( __FILE__, 'sut_wechat_mini_deactivate' );\nregister_uninstall_hook( __FILE__, 'sut_wechat_mini_uninstall' );\n\n/**\n * 鑾峰彇鎻掍欢瀹炰緥\n *\n * @return SUT_WeChat_Mini_Loader|null 鎻掍欢瀹炰緥\n */\nfunction sut_wechat_mini() {\n    static $instance = null;\n    \n    if ( is_null( $instance ) ) {\n        $instance = sut_wechat_mini_init();\n    }\n    \n    return $instance;\n}\n\n/**\n * 褰揥ordPress鍔犺浇瀹屾垚鍚庡垵濮嬪寲鎻掍欢\n */\nadd_action( 'plugins_loaded', 'sut_wechat_mini' );\n\n/**\n * 鑾峰彇鎻掍欢璁剧疆\n *\n * @return array 鎻掍欢璁剧疆\n */\nfunction sut_wechat_mini_get_settings() {\n    $loader = sut_wechat_mini();\n    \n    if ( $loader instanceof SUT_WeChat_Mini_Loader ) {\n        return $loader->get_settings();\n    }\n    \n    return array();\n}\n\n/**\n * 妫€鏌ユ彃浠舵槸鍚﹂厤缃纭?
 *\n * @return bool 鏄惁閰嶇疆姝ｇ‘\n */\nfunction sut_wechat_mini_is_configured() {\n    $loader = sut_wechat_mini();\n    \n    if ( $loader instanceof SUT_WeChat_Mini_Loader ) {\n        return $loader->is_configured();\n    }\n    \n    return false;\n}\n\n/**\n * 鑾峰彇鎻掍欢鐗堟湰鍙?
 *\n * @return string 鐗堟湰鍙?
 */\nfunction sut_wechat_mini_get_version() {\n    return SUT_WECHAT_MINI_VERSION;\n}\n\n/**\n * 鑾峰彇鎻掍欢鐩綍璺緞\n *\n * @return string 鐩綍璺緞\n */\nfunction sut_wechat_mini_get_plugin_dir() {\n    return SUT_WECHAT_MINI_PLUGIN_DIR;\n}\n\n/**\n * 鑾峰彇鎻掍欢URL\n *\n * @return string 鎻掍欢URL\n */\nfunction sut_wechat_mini_get_plugin_url() {\n    return SUT_WECHAT_MINI_PLUGIN_URL;\n}\n\n/**\n * 鑾峰彇璧勬簮鏂囦欢URL\n *\n * @param string $path 璧勬簮璺緞\n * @return string 璧勬簮URL\n */\nfunction sut_wechat_mini_get_asset_url( $path ) {\n    $loader = sut_wechat_mini();\n    \n    if ( $loader instanceof SUT_WeChat_Mini_Loader ) {\n        return $loader->get_asset_url( $path );\n    }\n    \n    return SUT_WECHAT_MINI_PLUGIN_URL . 'assets/' . ltrim( $path, '/' );\n}\n\n/**\n * 鑾峰彇API鍩虹URL\n *\n * @return string API鍩虹URL\n */\nfunction sut_wechat_mini_get_api_base_url() {\n    $loader = sut_wechat_mini();\n    \n    if ( $loader instanceof SUT_WeChat_Mini_Loader ) {\n        return $loader->get_api_base_url();\n    }\n    \n    return home_url( 'sut-wechat-mini-api/' );\n}\n\n/**\n * 鏃ュ織璁板綍鍑芥暟\n *\n * @param mixed $message 鏃ュ織娑堟伅\n * @param string $level 鏃ュ織绾у埆\n */\nfunction sut_wechat_mini_log( $message, $level = 'info' ) {\n    $settings = sut_wechat_mini_get_settings();\n    \n    // 妫€鏌ユ槸鍚﹀惎鐢ㄦ棩蹇?
    if ( empty( $settings['enable_log'] ) ) {\n        return;\n    }\n    \n    // 濡傛灉鏄璞℃垨鏁扮粍锛岃浆鎹负JSON\n    if ( is_object( $message ) || is_array( $message ) ) {\n        $message = json_encode( $message, JSON_UNESCAPED_UNICODE );\n    }\n    \n    // 鏋勫缓鏃ュ織鍐呭\n    $log_content = date( 'Y-m-d H:i:s' ) . ' [' . strtoupper( $level ) . '] ' . $message . "\n";\n    \n    // 鍐欏叆鏃ュ織鏂囦欢\n    $log_file = SUT_WECHAT_MINI_PLUGIN_DIR . 'logs/' . date( 'Y-m-d' ) . '.log';\n    \n    // 纭繚鏃ュ織鐩綍瀛樺湪\n    $log_dir = dirname( $log_file );\n    \n    if ( ! is_dir( $log_dir ) ) {\n        wp_mkdir_p( $log_dir );\n    }\n    \n    // 鍐欏叆鏃ュ織\n    file_put_contents( $log_file, $log_content, FILE_APPEND );\n}\n\n/**\n * 鏄剧ずAPI璇锋眰鐨勯敊璇俊鎭?
 *\n * @param string $message 閿欒娑堟伅\n * @param int $code 閿欒浠ｇ爜\n */\nfunction sut_wechat_mini_api_error( $message, $code = 1 ) {\n    wp_send_json_error( array(\n        'code' => $code,\n        'message' => $message\n    ) );\n}\n\n/**\n * 鏄剧ずAPI璇锋眰鐨勬垚鍔熶俊鎭?
 *\n * @param mixed $data 鍝嶅簲鏁版嵁\n * @param string $message 鎴愬姛娑堟伅\n */\nfunction sut_wechat_mini_api_success( $data = array(), $message = '鎿嶄綔鎴愬姛' ) {\n    wp_send_json_success( array(\n        'code' => 0,\n        'message' => $message,\n        'data' => $data\n    ) );\n}\n\n/**\n * 妫€鏌ョ敤鎴锋槸鍚︾櫥褰曪紙寰俊灏忕▼搴忕敤鎴凤級\n *\n * @return bool 鏄惁鐧诲綍\n */\nfunction sut_wechat_mini_is_user_logged_in() {\n    $user_id = get_current_user_id();\n    \n    if ( $user_id <= 0 ) {\n        return false;\n    }\n    \n    // 妫€鏌ョ敤鎴锋槸鍚︽湁灏忕▼搴忕敤鎴穖eta鏁版嵁\n    $wechat_openid = get_user_meta( $user_id, 'sut_wechat_mini_openid', true );\n    \n    return ! empty( $wechat_openid );\n}\n\n/**\n * 鑾峰彇褰撳墠鐧诲綍鐨勫皬绋嬪簭鐢ㄦ埛ID\n *\n * @return int 鐢ㄦ埛ID\n */\nfunction sut_wechat_mini_get_current_user_id() {\n    if ( sut_wechat_mini_is_user_logged_in() ) {\n        return get_current_user_id();\n    }\n    \n    return 0;\n}\n\n/**\n * 鑾峰彇灏忕▼搴忕敤鎴蜂俊鎭?
 *\n * @param int $user_id 鐢ㄦ埛ID\n * @return array 鐢ㄦ埛淇℃伅\n */\nfunction sut_wechat_mini_get_user_info( $user_id = 0 ) {\n    if ( empty( $user_id ) ) {\n        $user_id = sut_wechat_mini_get_current_user_id();\n    }\n    \n    if ( empty( $user_id ) ) {\n        return array();\n    }\n    \n    $user = get_user_by( 'id', $user_id );\n    \n    if ( ! $user ) {\n        return array();\n    }\n    \n    // 鑾峰彇鐢ㄦ埛鍩烘湰淇℃伅\n    $user_info = array(\n        'id' => $user->ID,\n        'username' => $user->user_login,\n        'nickname' => $user->display_name,\n        'avatar' => get_avatar_url( $user->ID ),\n        'email' => $user->user_email,\n        'register_date' => $user->user_registered,\n    );\n    \n    // 鑾峰彇灏忕▼搴忕壒瀹氱殑鐢ㄦ埛淇℃伅\n    $wechat_info = array(\n        'openid' => get_user_meta( $user_id, 'sut_wechat_mini_openid', true ),\n        'unionid' => get_user_meta( $user_id, 'sut_wechat_mini_unionid', true ),\n        'nickname' => get_user_meta( $user_id, 'sut_wechat_mini_nickname', true ),\n        'avatar' => get_user_meta( $user_id, 'sut_wechat_mini_avatar', true ),\n        'gender' => get_user_meta( $user_id, 'sut_wechat_mini_gender', true ),\n        'country' => get_user_meta( $user_id, 'sut_wechat_mini_country', true ),\n        'province' => get_user_meta( $user_id, 'sut_wechat_mini_province', true ),\n        'city' => get_user_meta( $user_id, 'sut_wechat_mini_city', true ),\n        'language' => get_user_meta( $user_id, 'sut_wechat_mini_language', true ),\n    );\n    \n    // 鍚堝苟淇℃伅\n    $user_info['wechat_info'] = $wechat_info;\n    \n    return $user_info;\n}\n\n/**\n * 妫€鏌ユ槸鍚﹀惎鐢ㄤ簡鐢靛晢鍔熻兘\n *\n * @return bool 鏄惁鍚敤\n */\nfunction sut_wechat_mini_is_ecommerce_enabled() {\n    return class_exists( 'WooCommerce' );\n}\n\n/**\n * 鑾峰彇鎻掍欢鏀寔鐨勫姛鑳藉垪琛?
 *\n * @return array 鍔熻兘鍒楄〃\n */\nfunction sut_wechat_mini_get_supported_features() {\n    $features = array(\n        'content' => true,       // 鍐呭灞曠ず\n        'users' => true,         // 鐢ㄦ埛绠＄悊\n        'messages' => true,      // 娑堟伅鎺ㄩ€?
        'points' => true,        // 绉垎绯荤粺\n        'cache' => true,         // 缂撳瓨绯荤粺\n    );\n    \n    // 妫€鏌ョ數鍟嗗姛鑳?
    $features['ecommerce'] = sut_wechat_mini_is_ecommerce_enabled();\n    \n    // 妫€鏌ユ敮浠樺姛鑳?
    if ( $features['ecommerce'] ) {\n        $settings = sut_wechat_mini_get_settings();\n        $features['payment'] = ! empty( $settings['mch_id'] ) && ! empty( $settings['api_key'] );\n    } else {\n        $features['payment'] = false;\n    }\n    \n    return $features;\n}\n\n/**\n * 妫€鏌ュ姛鑳芥槸鍚﹀彲鐢?
 *\n * @param string $feature 鍔熻兘鍚嶇О\n * @return bool 鏄惁鍙敤\n */\nfunction sut_wechat_mini_is_feature_available( $feature ) {\n    $features = sut_wechat_mini_get_supported_features();\n    \n    return isset( $features[ $feature ] ) && $features[ $feature ];\n}\n\n/**\n * 鑾峰彇鎻掍欢鐨勭姸鎬佷俊鎭?
 *\n * @return array 鐘舵€佷俊鎭?
 */\nfunction sut_wechat_mini_get_status() {\n    $status = array(\n        'version' => SUT_WECHAT_MINI_VERSION,\n        'configured' => sut_wechat_mini_is_configured(),\n        'php_version' => PHP_VERSION,\n        'wp_version' => get_bloginfo( 'version' ),\n        'features' => sut_wechat_mini_get_supported_features(),\n        'multisite' => is_multisite(),\n        'ssl' => is_ssl(),\n    );\n    \n    return $status;\n}\n\n/**\n * 鑾峰彇鎻掍欢鐨勮皟璇曚俊鎭?
 *\n * @return array 璋冭瘯淇℃伅\n */\nfunction sut_wechat_mini_get_debug_info() {\n    $debug_info = array(\n        'status' => sut_wechat_mini_get_status(),\n        'settings' => sut_wechat_mini_get_settings(),\n        'constants' => array(\n            'SUT_WECHAT_MINI_VERSION' => SUT_WECHAT_MINI_VERSION,\n            'SUT_WECHAT_MINI_PLUGIN_DIR' => SUT_WECHAT_MINI_PLUGIN_DIR,\n            'SUT_WECHAT_MINI_PLUGIN_URL' => SUT_WECHAT_MINI_PLUGIN_URL,\n            'SUT_WECHAT_MINI_PLUGIN_FILE' => SUT_WECHAT_MINI_PLUGIN_FILE,\n            'SUT_WECHAT_MINI_PLUGIN_BASENAME' => SUT_WECHAT_MINI_PLUGIN_BASENAME,\n            'ABSPATH' => ABSPATH,\n        ),\n        'server' => array(\n            'PHP_OS' => PHP_OS,\n            'SERVER_SOFTWARE' => isset( $_SERVER['SERVER_SOFTWARE'] ) ? $_SERVER['SERVER_SOFTWARE'] : '',\n            'PHP_MAX_INPUT_VARS' => ini_get( 'max_input_vars' ),\n            'PHP_MAX_EXECUTION_TIME' => ini_get( 'max_execution_time' ),\n            'PHP_MEMORY_LIMIT' => ini_get( 'memory_limit' ),\n        ),\n        'active_plugins' => get_option( 'active_plugins', array() ),\n        'theme' => wp_get_theme()->get( 'Name' ) . ' ' . wp_get_theme()->get( 'Version' ),\n    );\n    \n    return $debug_info;\n}