锘?/ pages/user/login/login.js\n/**\n * 閻ц缍嶆い鐢告桨 - 婢跺嫮鎮婇悽銊﹀煕閹哄牊娼堥崪宀€娅ヨぐ鏇⑩偓鏄忕帆\n */\nimport { showToast } from '../../../utils/global';\n\nPage({\n  data: {\n    canIUseGetUserProfile: false, // 閺勵垰鎯侀弨顖涘瘮getUserProfile閺傝纭禱n    canIUseOpenData: wx.canIUse('open-data.type.userAvatarUrl') && wx.canIUse('open-data.type.userNickName'), // 閺勵垰鎯侀弨顖涘瘮瀵偓閺€鐐殶閹?
    isLoading: false, // 閸旂姾娴囬悩鑸碘偓?
    showSkeleton: true, // 妤犮劍鐏︾仦蹇旀▔缁€铏瑰Ц閹?
    privacyPolicyAccepted: false, // 闂呮劗顫嗛弨璺ㄧ摜閸氬本鍓伴悩鑸碘偓?
    errorMessage: '', // 闁挎瑨顕ら幓鎰仛娣団剝浼匼n    appVersion: '', // 鎼存梻鏁ら悧鍫熸拱閸?
    showFeatures: true // 閺勵垰鎯侀弰鍓с仛閸旂喕鍏樼拠瀛樻\n  },\n\n  /**\n   * 閻㈢喎鎳￠崨銊︽埂閸戣姤鏆?-閻╂垵鎯夋い鐢告桨閸旂姾娴嘰n   */\n  onLoad: function() {\n    // 閸掓繂顫愰崠鏍€囬弸璺虹潌\n    this.setData({\n      showSkeleton: true\n    });\n\n    // 濡偓閺屻儲妲搁崥锔芥暜閹镐宫etUserProfile閺傝纭堕敍鍫濅簳娣団€崇毈缁嬪绨崺铏诡攨鎼?.10.4閸欏﹣浜掓稉濠勫閺堫剚鏁幐渚婄礆\n    if (wx.getUserProfile) {\n      this.setData({\n        canIUseGetUserProfile: true\n      });\n    }\n\n    // 濡偓閺屻儲妲搁崥锕€鍑＄紒蹇曟瑜?
    const app = getApp();\n    if (app.isLoggedIn()) {\n      wx.switchTab({\n        url: '/pages/user/profile/profile'\n      });\n      return;\n    }\n    \n    // 閼惧嘲褰囨惔鏃傛暏閻楀牊婀伴崣?
    try {\n      const { version } = wx.getAccountInfoSync();\n      this.setData({\n        appVersion: version\n      });\n    } catch (e) {\n      console.error('閼惧嘲褰囬悧鍫熸拱閸欏嘲銇戠拹?', e);\n    } finally {\n      // 妞ょ敻娼伴崚婵嗩潗閸栨牕鐣幋鎰倵闂呮劘妫屾銊︾仸鐏?
      setTimeout(() => {\n        this.setData({\n          showSkeleton: false\n        });\n      }, 800);\n    }\n  },\n\n  /**\n   * 閻㈢喎鎳￠崨銊︽埂閸戣姤鏆?-閻╂垵鎯夋い鐢告桨閺勫墽銇歕n   */\n  onShow: function() {\n    // 妞ょ敻娼伴弰鍓с仛閺冨墎娈戦柅鏄忕帆\n  },\n\n  /**\n   * 閼惧嘲褰囬悽銊﹀煕娣団剝浼呴獮鍓佹瑜版洩绱欐担璺ㄦ暏getUserProfile閺傝纭堕敍灞惧腹閼芥劒濞囬悽顭掔礆\n   */\n  getUserProfile: function() {\n    // 濡偓閺屻儲妲搁崥锕€鎮撻幇蹇涙缁変焦鏂傜粵?
    if (!this.data.privacyPolicyAccepted) {\n      wx.showToast({\n        title: '鐠囧嘲鍘涢梼鍛邦嚢楠炶泛鎮撻幇蹇涙缁変焦鏂傜粵鏍ф嫲閻劍鍩涢崡蹇氼唴',\n        icon: 'none'\n      });\n      return;\n    }\n\n    const that = this;\n    \n    wx.getUserProfile({\n      desc: '閻劋绨€瑰苯鏉介悽銊﹀煕鐠у嫭鏋?,\n      success: (res) => {\n        // 閼惧嘲褰囬悽銊﹀煕娣団剝浼呴幋鎰閿涘矁鐨熼悽銊ф瑜版洘鏌熷▔?
        that.userLogin(res.userInfo);\n      },\n      fail: (err) => {\n        console.error('閼惧嘲褰囬悽銊﹀煕娣団剝浼呮径杈Е:', err);\n        this.setData({\n          isLoading: false,\n          errorMessage: '閼惧嘲褰囬悽銊﹀煕娣団剝浼呮径杈Е'\n        });\n        wx.showToast({\n          title: '閼惧嘲褰囬悽銊﹀煕娣団剝浼呮径杈Е',\n          icon: 'none',\n          duration: 2000\n        });\n      }\n    });\n  },\n\n  /**\n   * 娴肩姷绮洪惃鍕箯閸欐牜鏁ら幋铚備繆閹垱鏌熷▔鏇礄閸忕厧顔愰幀褍顦╅悶鍡礆\n   */\n  bindGetUserInfo: function(e) {\n    // 濡偓閺屻儲妲搁崥锕€鎮撻幇蹇涙缁変焦鏂傜粵?
    if (!this.data.privacyPolicyAccepted) {\n      wx.showToast({\n        title: '鐠囧嘲鍘涢梼鍛邦嚢楠炶泛鎮撻幇蹇涙缁変焦鏂傜粵鏍ф嫲閻劍鍩涢崡蹇氼唴',\n        icon: 'none'\n      });\n      return;\n    }\n\n    if (e.detail.userInfo) {\n      // 閻劍鍩涢崥灞惧壈閹哄牊娼圽n      this.userLogin(e.detail.userInfo);\n    } else {\n      // 閻劍鍩涢幏鎺旂卜閹哄牊娼圽n      wx.showToast({\n        title: '闂団偓鐟曚焦宸块弶鍐╁閼虫垝濞囬悽銊ョ暚閺佹潙濮涢懗?,\n        icon: 'none',\n        duration: 2000\n      });\n    }\n  },\n\n  /**\n   * 閹笛嗩攽閻ц缍嶉幙宥勭稊\n   * @param {Object} userInfo - 閻劍鍩涙穱鈩冧紖鐎电钖刓n   */\n  userLogin: async function(userInfo) {\n    const that = this;\n    const app = getApp();\n    \n    // 閺勫墽銇氶崝鐘烘祰閻樿埖鈧?
    that.setData({\n      isLoading: true,\n      errorMessage: ''\n    });\n    \n    try {\n      // 娴ｈ法鏁uth-service鏉╂稖顢戦惂璇茬秿\n      const result = await app.services.auth.login(userInfo);\n      \n      if (result.success) {\n        // 閹绘劗銇氶惂璇茬秿閹存劕濮沑n        showToast('閻ц缍嶉幋鎰', 'success');\n        \n        // 鐠哄疇娴嗛崚棰侀嚋娴滆桨鑵戣箛鍐€夐棃?
        setTimeout(() => {\n          wx.switchTab({\n            url: '/pages/user/profile/profile'\n          });\n        }, 1500);\n      } else {\n        throw new Error(result.message || '閻ц缍嶆径杈Е');\n      }\n    } catch (error) {\n      console.error('閻ц缍嶆径杈Е:', error);\n      const errorMsg = error.message || '閻ц缍嶆径杈Е閿涘矁顕粙宥呮倵闁插秷鐦?;\n      this.setData({\n        errorMessage: errorMsg\n      });\n      showToast(errorMsg, 'none', 2000);\n      // 5缁夋帒鎮楀〒鍛存珟闁挎瑨顕ゅ☉鍫熶紖\n      setTimeout(() => {\n        this.setData({\n          errorMessage: ''\n        });\n      }, 5000);\n    } finally {\n      that.setData({\n        isLoading: false\n      });\n    }\n  },\n\n  /**\n   * 婢跺嫮鎮婇悽銊﹀煕閸欐牗绉烽幒鍫熸綀閻ㄥ嫭鍎忛崘?
   */\n  onAuthCancel: function() {\n    showToast('闂団偓鐟曚焦宸块弶鍐╁閼虫垝濞囬悽銊ョ暚閺佹潙濮涢懗?, 'none', 2000);\n  },\n\n  /**\n   * 閼辨梻閮寸€广垺婀嘰n   */\n  contactService: function() {\n    wx.makePhoneCall({\n      phoneNumber: '400-123-4567', // 閺囨寧宕叉稉鍝勭杽闂勫懐娈戠€广垺婀囬悽浣冪樈\n      fail: function() {\n        showToast('閹枫劍澧︽径杈Е閿涘矁顕粙宥呮倵閸愬秷鐦?, 'none');\n      }\n    });\n  },\n\n  /**\n   * 闁插秷鐦惂璇茬秿\n   */\n  onRetry: function() {\n    this.setData({\n      errorMessage: '',\n      showSkeleton: true\n    });\n    \n    // 濡剝瀚欓柌宥嗘煀閸旂姾娴囨い鐢告桨\n    setTimeout(() => {\n      this.setData({\n        showSkeleton: false\n      });\n    }, 500);\n  },\n\n  /**\n   * 鐠哄疇娴嗛崡蹇氼唴妞ょ敻娼癨n   */\n  navigateToAgreement: function(e) {\n    const type = e.currentTarget.dataset.type;\n    \n    // 鐠哄疇娴嗛崚鏉垮嚒缂佸繐鍨卞铏规畱閸楀繗顔呮い鐢告桨\n    wx.navigateTo({\n      url: `/pages/user/agreement/agreement?type=${type}`,\n      fail: function() {\n        wx.showToast({\n          title: '鐠哄疇娴嗘径杈Е閿涘矁顕粙宥呮倵閸愬秷鐦?,\n          icon: 'none'\n        });\n      }\n    });\n  },\n\n  /**\n   * 閸掑洦宕查梾鎰潌閺€璺ㄧ摜閸氬本鍓伴悩鑸碘偓?
   */\n  togglePrivacyPolicy: function() {\n    this.setData({\n      privacyPolicyAccepted: !this.data.privacyPolicyAccepted\n    });\n  }\n});\n