// pages/user/login/login.js\n/**\n * 鐧诲綍椤甸潰 - 澶勭悊鐢ㄦ埛鎺堟潈鍜岀櫥褰曢€昏緫\n */\nimport { showToast } from '../../../utils/global';\n\nPage({\n  data: {\n    canIUseGetUserProfile: false, // 鏄惁鏀寔getUserProfile鏂规硶\n    canIUseOpenData: wx.canIUse('open-data.type.userAvatarUrl') && wx.canIUse('open-data.type.userNickName'), // 鏄惁鏀寔寮€鏀炬暟鎹?
    isLoading: false, // 鍔犺浇鐘舵€?
    showSkeleton: true, // 楠ㄦ灦灞忔樉绀虹姸鎬?
    privacyPolicyAccepted: false, // 闅愮鏀跨瓥鍚屾剰鐘舵€?
    errorMessage: '', // 閿欒鎻愮ず淇℃伅\n    appVersion: '', // 搴旂敤鐗堟湰鍙?
    showFeatures: true // 鏄惁鏄剧ず鍔熻兘璇存槑\n  },\n\n  /**\n   * 鐢熷懡鍛ㄦ湡鍑芥暟--鐩戝惉椤甸潰鍔犺浇\n   */\n  onLoad: function() {\n    // 鍒濆鍖栭鏋跺睆\n    this.setData({\n      showSkeleton: true\n    });\n\n    // 妫€鏌ユ槸鍚︽敮鎸乬etUserProfile鏂规硶锛堝井淇″皬绋嬪簭鍩虹搴?.10.4鍙婁互涓婄増鏈敮鎸侊級\n    if (wx.getUserProfile) {\n      this.setData({\n        canIUseGetUserProfile: true\n      });\n    }\n\n    // 妫€鏌ユ槸鍚﹀凡缁忕櫥褰?
    const app = getApp();\n    if (app.isLoggedIn()) {\n      wx.switchTab({\n        url: '/pages/user/profile/profile'\n      });\n      return;\n    }\n    \n    // 鑾峰彇搴旂敤鐗堟湰鍙?
    try {\n      const { version } = wx.getAccountInfoSync();\n      this.setData({\n        appVersion: version\n      });\n    } catch (e) {\n      console.error('鑾峰彇鐗堟湰鍙峰け璐?', e);\n    } finally {\n      // 椤甸潰鍒濆鍖栧畬鎴愬悗闅愯棌楠ㄦ灦灞?
      setTimeout(() => {\n        this.setData({\n          showSkeleton: false\n        });\n      }, 800);\n    }\n  },\n\n  /**\n   * 鐢熷懡鍛ㄦ湡鍑芥暟--鐩戝惉椤甸潰鏄剧ず\n   */\n  onShow: function() {\n    // 椤甸潰鏄剧ず鏃剁殑閫昏緫\n  },\n\n  /**\n   * 鑾峰彇鐢ㄦ埛淇℃伅骞剁櫥褰曪紙浣跨敤getUserProfile鏂规硶锛屾帹鑽愪娇鐢級\n   */\n  getUserProfile: function() {\n    // 妫€鏌ユ槸鍚﹀悓鎰忛殣绉佹斂绛?
    if (!this.data.privacyPolicyAccepted) {\n      wx.showToast({\n        title: '璇峰厛闃呰骞跺悓鎰忛殣绉佹斂绛栧拰鐢ㄦ埛鍗忚',\n        icon: 'none'\n      });\n      return;\n    }\n\n    const that = this;\n    \n    wx.getUserProfile({\n      desc: '鐢ㄤ簬瀹屽杽鐢ㄦ埛璧勬枡',\n      success: (res) => {\n        // 鑾峰彇鐢ㄦ埛淇℃伅鎴愬姛锛岃皟鐢ㄧ櫥褰曟柟娉?
        that.userLogin(res.userInfo);\n      },\n      fail: (err) => {\n        console.error('鑾峰彇鐢ㄦ埛淇℃伅澶辫触:', err);\n        this.setData({\n          isLoading: false,\n          errorMessage: '鑾峰彇鐢ㄦ埛淇℃伅澶辫触'\n        });\n        wx.showToast({\n          title: '鑾峰彇鐢ㄦ埛淇℃伅澶辫触',\n          icon: 'none',\n          duration: 2000\n        });\n      }\n    });\n  },\n\n  /**\n   * 浼犵粺鐨勮幏鍙栫敤鎴蜂俊鎭柟娉曪紙鍏煎鎬у鐞嗭級\n   */\n  bindGetUserInfo: function(e) {\n    // 妫€鏌ユ槸鍚﹀悓鎰忛殣绉佹斂绛?
    if (!this.data.privacyPolicyAccepted) {\n      wx.showToast({\n        title: '璇峰厛闃呰骞跺悓鎰忛殣绉佹斂绛栧拰鐢ㄦ埛鍗忚',\n        icon: 'none'\n      });\n      return;\n    }\n\n    if (e.detail.userInfo) {\n      // 鐢ㄦ埛鍚屾剰鎺堟潈\n      this.userLogin(e.detail.userInfo);\n    } else {\n      // 鐢ㄦ埛鎷掔粷鎺堟潈\n      wx.showToast({\n        title: '闇€瑕佹巿鏉冩墠鑳戒娇鐢ㄥ畬鏁村姛鑳?,\n        icon: 'none',\n        duration: 2000\n      });\n    }\n  },\n\n  /**\n   * 鎵ц鐧诲綍鎿嶄綔\n   * @param {Object} userInfo - 鐢ㄦ埛淇℃伅瀵硅薄\n   */\n  userLogin: async function(userInfo) {\n    const that = this;\n    const app = getApp();\n    \n    // 鏄剧ず鍔犺浇鐘舵€?
    that.setData({\n      isLoading: true,\n      errorMessage: ''\n    });\n    \n    try {\n      // 浣跨敤auth-service杩涜鐧诲綍\n      const result = await app.services.auth.login(userInfo);\n      \n      if (result.success) {\n        // 鎻愮ず鐧诲綍鎴愬姛\n        showToast('鐧诲綍鎴愬姛', 'success');\n        \n        // 璺宠浆鍒颁釜浜轰腑蹇冮〉闈?
        setTimeout(() => {\n          wx.switchTab({\n            url: '/pages/user/profile/profile'\n          });\n        }, 1500);\n      } else {\n        throw new Error(result.message || '鐧诲綍澶辫触');\n      }\n    } catch (error) {\n      console.error('鐧诲綍澶辫触:', error);\n      const errorMsg = error.message || '鐧诲綍澶辫触锛岃绋嶅悗閲嶈瘯';\n      this.setData({\n        errorMessage: errorMsg\n      });\n      showToast(errorMsg, 'none', 2000);\n      // 5绉掑悗娓呴櫎閿欒娑堟伅\n      setTimeout(() => {\n        this.setData({\n          errorMessage: ''\n        });\n      }, 5000);\n    } finally {\n      that.setData({\n        isLoading: false\n      });\n    }\n  },\n\n  /**\n   * 澶勭悊鐢ㄦ埛鍙栨秷鎺堟潈鐨勬儏鍐?
   */\n  onAuthCancel: function() {\n    showToast('闇€瑕佹巿鏉冩墠鑳戒娇鐢ㄥ畬鏁村姛鑳?, 'none', 2000);\n  },\n\n  /**\n   * 鑱旂郴瀹㈡湇\n   */\n  contactService: function() {\n    wx.makePhoneCall({\n      phoneNumber: '400-123-4567', // 鏇挎崲涓哄疄闄呯殑瀹㈡湇鐢佃瘽\n      fail: function() {\n        showToast('鎷ㄦ墦澶辫触锛岃绋嶅悗鍐嶈瘯', 'none');\n      }\n    });\n  },\n\n  /**\n   * 閲嶈瘯鐧诲綍\n   */\n  onRetry: function() {\n    this.setData({\n      errorMessage: '',\n      showSkeleton: true\n    });\n    \n    // 妯℃嫙閲嶆柊鍔犺浇椤甸潰\n    setTimeout(() => {\n      this.setData({\n        showSkeleton: false\n      });\n    }, 500);\n  },\n\n  /**\n   * 璺宠浆鍗忚椤甸潰\n   */\n  navigateToAgreement: function(e) {\n    const type = e.currentTarget.dataset.type;\n    \n    // 璺宠浆鍒板凡缁忓垱寤虹殑鍗忚椤甸潰\n    wx.navigateTo({\n      url: `/pages/user/agreement/agreement?type=${type}`,\n      fail: function() {\n        wx.showToast({\n          title: '璺宠浆澶辫触锛岃绋嶅悗鍐嶈瘯',\n          icon: 'none'\n        });\n      }\n    });\n  },\n\n  /**\n   * 鍒囨崲闅愮鏀跨瓥鍚屾剰鐘舵€?
   */\n  togglePrivacyPolicy: function() {\n    this.setData({\n      privacyPolicyAccepted: !this.data.privacyPolicyAccepted\n    });\n  }\n});\n