// cache.js - 鏈湴缂撳瓨宸ュ叿绫?
// 鍩轰簬鎶€鏈璁℃枃妗ｅ疄鐜扮殑缂撳瓨绠＄悊妯″潡\n\n// 缂撳瓨閿墠缂€\nconst CACHE_PREFIX = 'sut_wxcache_';\n\n// 缂撳瓨閿父閲忓璞★紝缁熶竴绠＄悊缂撳瓨閿?
export const CACHE_KEYS = {\n  // 鐢ㄦ埛鐩稿叧\n  USER_INFO: 'user_info',\n  TOKEN: 'user_token',\n  \n  // 鍐呭鐩稿叧\n  HOT_ARTICLES: 'hot_articles',\n  ARTICLE_LIST: 'article_list_',\n  ARTICLE_DETAIL_PREFIX: 'article_detail_',\n  \n  // 鐢靛晢鐩稿叧\n  CART_DATA: 'cart_data',\n  COUPON_LIST_PREFIX: 'coupon_list_',\n  COUPON_DETAIL_PREFIX: 'coupon_detail_',\n  \n  // 鍒嗙被鐩稿叧\n  CATEGORY_LIST: 'category_list',\n  \n  // 鎼滅储鐩稿叧\n  SEARCH_HISTORY: 'search_history',\n  \n  // 绯荤粺閰嶇疆\n  SYSTEM_CONFIG: 'system_config'\n};\n\n// 缂撳瓨鏃堕暱甯搁噺锛堢锛?
export const CACHE_DURATION = {\n  SHORT: 300, // 5鍒嗛挓\n  MEDIUM: 1800, // 30鍒嗛挓\n  LONG: 3600, // 1灏忔椂\n  HIGH_FREQUENCY: 60, // 1鍒嗛挓锛堥珮棰戞洿鏂版暟鎹級\n  VERY_LONG: 86400 // 24灏忔椂锛堜笉甯稿彉鍔ㄦ暟鎹級\n};\n\n// 鍩虹缂撳瓨鏂规硶\nconst cache = {\n  /**\n   * 璁剧疆缂撳瓨\n   * @param {string} key - 缂撳瓨閿?
   * @param {*} value - 缂撳瓨鍊?
   * @param {number} expiry - 杩囨湡鏃堕棿锛堢锛夛紝null琛ㄧず姘镐笉杩囨湡\n   */\n  set(key, value, expiry = CACHE_DURATION.MEDIUM) {\n    try {\n      const data = {\n        value,\n        expiry: expiry ? Date.now() + expiry * 1000 : null\n      };\n      wx.setStorageSync(`${CACHE_PREFIX}${key}`, data);\n    } catch (error) {\n      console.error('璁剧疆缂撳瓨澶辫触:', error);\n    }\n  },\n  \n  /**\n   * 鑾峰彇缂撳瓨\n   * @param {string} key - 缂撳瓨閿?
   * @returns {*} 缂撳瓨鍊硷紝濡傛灉杩囨湡鎴栦笉瀛樺湪杩斿洖null\n   */\n  get(key) {\n    try {\n      const data = wx.getStorageSync(`${CACHE_PREFIX}${key}`);\n      if (!data) return null;\n      \n      // 妫€鏌ユ槸鍚﹁繃鏈?
      if (data.expiry && Date.now() > data.expiry) {\n        this.remove(key);\n        return null;\n      }\n      \n      return data.value;\n    } catch (error) {\n      console.error('鑾峰彇缂撳瓨澶辫触:', error);\n      return null;\n    }\n  },\n  \n  /**\n   * 鍒犻櫎缂撳瓨\n   * @param {string} key - 缂撳瓨閿?
   */\n  remove(key) {\n    try {\n      wx.removeStorageSync(`${CACHE_PREFIX}${key}`);\n    } catch (error) {\n      console.error('鍒犻櫎缂撳瓨澶辫触:', error);\n    }\n  },\n  \n  /**\n   * 娓呴櫎鎵€鏈夌紦瀛?
   */\n  clear() {\n    try {\n      const keys = wx.getStorageInfoSync().keys;\n      keys.forEach(key => {\n        if (key.startsWith(CACHE_PREFIX)) {\n          wx.removeStorageSync(key);\n        }\n      });\n    } catch (error) {\n      console.error('娓呴櫎缂撳瓨澶辫触:', error);\n    }\n  },\n  \n  /**\n   * 娓呴櫎鍖归厤鍓嶇紑鐨勭紦瀛?
   * @param {string} prefix - 缂撳瓨閿墠缂€\n   */\n  clearByPrefix(prefix) {\n    try {\n      const fullPrefix = `${CACHE_PREFIX}${prefix}`;\n      const keys = wx.getStorageInfoSync().keys;\n      keys.forEach(key => {\n        if (key.startsWith(fullPrefix)) {\n          wx.removeStorageSync(key);\n        }\n      });\n    } catch (error) {\n      console.error('娓呴櫎鍓嶇紑缂撳瓨澶辫触:', error);\n    }\n  }\n};\n\n// 缂撳瓨绠＄悊绫?
export default class CacheManager {\n  // 鐢ㄦ埛鐩稿叧缂撳瓨\n  static getUserInfo() {\n    return cache.get(CACHE_KEYS.USER_INFO);\n  }\n  \n  static setUserInfo(userInfo) {\n    return cache.set(CACHE_KEYS.USER_INFO, userInfo, CACHE_DURATION.LONG);\n  }\n  \n  // 鏂囩珷鐩稿叧缂撳瓨\n  static getHotArticles() {\n    return cache.get(CACHE_KEYS.HOT_ARTICLES);\n  }\n  \n  static setHotArticles(articles) {\n    cache.set(CACHE_KEYS.HOT_ARTICLES, articles, CACHE_DURATION.SHORT);\n  }\n  \n  static getArticleList(page, category = '') {\n    const key = `${CACHE_KEYS.ARTICLE_LIST}${category || 'all'}_${page}`;\n    return cache.get(key);\n  }\n  \n  static setArticleList(page, articles, category = '') {\n    const key = `${CACHE_KEYS.ARTICLE_LIST}${category || 'all'}_${page}`;\n    cache.set(key, articles, CACHE_DURATION.MEDIUM);\n  }\n  \n  static getArticleDetail(id) {\n    return cache.get(`${CACHE_KEYS.ARTICLE_DETAIL_PREFIX}${id}`);\n  }\n  \n  static setArticleDetail(id, article) {\n    cache.set(`${CACHE_KEYS.ARTICLE_DETAIL_PREFIX}${id}`, article, CACHE_DURATION.LONG);\n  }\n  \n  // 璐墿杞︾浉鍏崇紦瀛?
  static getCartData() {\n    return cache.get(CACHE_KEYS.CART_DATA) || [];\n  }\n  \n  static setCartData(cartData) {\n    cache.set(CACHE_KEYS.CART_DATA, cartData, CACHE_DURATION.VERY_LONG);\n  }\n  \n  // 浼樻儬鍒哥浉鍏崇紦瀛?
  static getCouponList(status = 'available') {\n    return cache.get(`${CACHE_KEYS.COUPON_LIST_PREFIX}${status}`);\n  }\n  \n  static setCouponList(coupons, status = 'available') {\n    const duration = status === 'available' ? CACHE_DURATION.SHORT : CACHE_DURATION.MEDIUM;\n    cache.set(`${CACHE_KEYS.COUPON_LIST_PREFIX}${status}`, coupons, duration);\n  }\n  \n  static getCouponDetail(id) {\n    return cache.get(`${CACHE_KEYS.COUPON_DETAIL_PREFIX}${id}`);\n  }\n  \n  static setCouponDetail(id, coupon) {\n    cache.set(`${CACHE_KEYS.COUPON_DETAIL_PREFIX}${id}`, coupon, CACHE_DURATION.LONG);\n  }\n  \n  // 鍒嗙被鐩稿叧缂撳瓨\n  static getCategoryList() {\n    return cache.get(CACHE_KEYS.CATEGORY_LIST);\n  }\n  \n  static setCategoryList(categories) {\n    cache.set(CACHE_KEYS.CATEGORY_LIST, categories, CACHE_DURATION.LONG);\n  }\n  \n  // 娓呴櫎鐗瑰畾缂撳瓨\n  static clearArticleCache(id) {\n    cache.remove(`${CACHE_KEYS.ARTICLE_DETAIL_PREFIX}${id}`);\n  }\n  \n  static clearCouponCache(statuses = ['available', 'used', 'expired']) {\n    statuses.forEach(status => {\n      cache.remove(`${CACHE_KEYS.COUPON_LIST_PREFIX}${status}`);\n    });\n  }\n  \n  static clearCartCache() {\n    cache.remove(CACHE_KEYS.CART_DATA);\n  }\n  \n  static clearContentCache() {\n    cache.remove(CACHE_KEYS.HOT_ARTICLES);\n    cache.clearByPrefix(CACHE_KEYS.ARTICLE_LIST);\n    cache.clearByPrefix(CACHE_KEYS.ARTICLE_DETAIL_PREFIX);\n  }\n  \n  static clearUserCache() {\n    cache.remove(CACHE_KEYS.USER_INFO);\n    cache.remove(CACHE_KEYS.TOKEN);\n  }\n  \n  static clearAllCache() {\n    cache.clear();\n  }\n}\n\n// 瀵煎嚭閫氱敤缂撳瓨鍑芥暟\nexport const setCache = cache.set;\nexport const getCache = cache.get;\nexport const removeCache = cache.remove;\nexport const clearCache = cache.clear;\nexport const clearCacheByPrefix = cache.clearByPrefix;\n