/**
 * 文件名: productService.mock.js
 * 版本号: 3.0.9
 * 更新日期: 2026-09-12
 * 描述: 商品服务层的演示数据（'mock' 数据源），从 productService.js 抽离以保持单文件精简
 */

const mockProducts = [
  {
    id: 1,
    name: "绿萝盆栽",
    price: 29.9,
    originPrice: 39.9,
    image: "/images/placeholder.svg",
    images: ["/images/placeholder.svg"],
    categoryId: 2,
    categoryName: "绿色植物",
    sales: 1288,
    stock: 100,
    desc: "室内净化空气必备",
    description: "绿萝是净化空气的最佳植物之一，适合放在室内养护",
    isFavorite: false,
    rating: 4.8,
    reviewCount: 256,
    specs: [{ id: 0, name: "默认规格", price: 29.9, stock: 100 }],
  },
  {
    id: 2,
    name: "多肉植物组合",
    price: 49.9,
    originPrice: 69.9,
    image: "/images/placeholder.svg",
    images: ["/images/placeholder.svg"],
    categoryId: 3,
    categoryName: "多肉植物",
    sales: 968,
    stock: 50,
    desc: "5株精美多肉组合",
    description: "精选5种不同的多肉植物，包含精美花盆",
    isFavorite: false,
    rating: 4.9,
    reviewCount: 189,
    specs: [{ id: 0, name: "默认规格", price: 49.9, stock: 50 }],
  },
  {
    id: 3,
    name: "发财树",
    price: 88.0,
    originPrice: 128.0,
    image: "/images/placeholder.svg",
    images: ["/images/placeholder.svg"],
    categoryId: 2,
    categoryName: "绿色植物",
    sales: 756,
    stock: 30,
    desc: "寓意吉祥，招财进宝",
    description: "发财树寓意吉祥，适合放在办公室或家中",
    isFavorite: false,
    rating: 4.7,
    reviewCount: 134,
    specs: [{ id: 0, name: "默认规格", price: 88.0, stock: 30 }],
  },
  {
    id: 4,
    name: "蝴蝶兰盆栽",
    price: 128.0,
    originPrice: 168.0,
    image: "/images/placeholder.svg",
    images: ["/images/placeholder.svg"],
    categoryId: 4,
    categoryName: "鲜花花卉",
    sales: 526,
    stock: 25,
    desc: "高雅优美，送礼首选",
    description: "精选优质蝴蝶兰，花期长，花色艳丽",
    isFavorite: false,
    rating: 4.9,
    reviewCount: 98,
    specs: [{ id: 0, name: "默认规格", price: 128.0, stock: 25 }],
  },
  {
    id: 5,
    name: "陶瓷花盆",
    price: 39.9,
    originPrice: 59.9,
    image: "/images/placeholder.svg",
    images: ["/images/placeholder.svg"],
    categoryId: 5,
    categoryName: "花盆花器",
    sales: 1356,
    stock: 200,
    desc: "简约现代风格",
    description: "优质陶瓷材质，简约现代设计",
    isFavorite: false,
    rating: 4.6,
    reviewCount: 312,
    specs: [{ id: 0, name: "默认规格", price: 39.9, stock: 200 }],
  },
  {
    id: 6,
    name: "营养土",
    price: 19.9,
    originPrice: 29.9,
    image: "/images/placeholder.svg",
    images: ["/images/placeholder.svg"],
    categoryId: 7,
    categoryName: "营养土肥",
    sales: 2568,
    stock: 500,
    desc: "专用营养土",
    description: "专门为绿植配置的营养土，富含养分",
    isFavorite: false,
    rating: 4.8,
    reviewCount: 456,
    specs: [{ id: 0, name: "默认规格", price: 19.9, stock: 500 }],
  },
];

module.exports = { mockProducts };
