/**
 * 文件名: eslint.config.js
 * 版本号: 3.0.10
 * 更新日期: 2026-09-13
 * 描述: ESLint 10 扁平配置（flat config），完全自包含、不依赖任何外部包。
 *       recommended 规则与 node 全局变量精确复刻原 .eslintrc.js 在 eslint 8 下的行为，
 *       以保证 lint 通过状态与升级前一致。
 */
// eslint 8 的 eslint:recommended 规则集（全部在 eslint 10 中仍存在）
const recommendedRules = {
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-case-declarations": "error",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": "error",
  "no-const-assign": "error",
  "no-constant-condition": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-delete-var": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-ex-assign": "error",
  "no-extra-boolean-cast": "error",
  "no-extra-semi": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-global-assign": "error",
  "no-import-assign": "error",
  "no-inner-declarations": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-mixed-spaces-and-tabs": "error",
  "no-new-symbol": "error",
  "no-nonoctal-decimal-escape": "error",
  "no-obj-calls": "error",
  "no-octal": "error",
  "no-prototype-builtins": "error",
  "no-redeclare": "error",
  "no-regex-spaces": "error",
  "no-self-assign": "error",
  "no-setter-return": "error",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-this-before-super": "error",
  "no-undef": "error",
  "no-unexpected-multiline": "error",
  "no-unreachable": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-labels": "error",
  "no-unused-vars": "error",
  "no-useless-backreference": "error",
  "no-useless-catch": "error",
  "no-useless-escape": "error",
  "no-with": "error",
  "require-yield": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
};

// node 运行环境全局变量（复刻 env.node，等价于 globals@13 的 node 导出）
const nodeGlobals = {
  __dirname: "readonly",
  __filename: "readonly",
  AbortController: "readonly",
  AbortSignal: "readonly",
  atob: "readonly",
  Blob: "readonly",
  BroadcastChannel: "readonly",
  btoa: "readonly",
  Buffer: "readonly",
  ByteLengthQueuingStrategy: "readonly",
  clearImmediate: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  CompressionStream: "readonly",
  console: "readonly",
  CountQueuingStrategy: "readonly",
  crypto: "readonly",
  Crypto: "readonly",
  CryptoKey: "readonly",
  CustomEvent: "readonly",
  DecompressionStream: "readonly",
  DOMException: "readonly",
  Event: "readonly",
  EventTarget: "readonly",
  exports: "writable",
  fetch: "readonly",
  File: "readonly",
  FormData: "readonly",
  global: "readonly",
  Headers: "readonly",
  Intl: "readonly",
  MessageChannel: "readonly",
  MessageEvent: "readonly",
  MessagePort: "readonly",
  module: "writable",
  PerformanceEntry: "readonly",
  PerformanceMark: "readonly",
  PerformanceMeasure: "readonly",
  PerformanceObserver: "readonly",
  PerformanceObserverEntryList: "readonly",
  PerformanceResourceTiming: "readonly",
  process: "readonly",
  queueMicrotask: "readonly",
  ReadableByteStreamController: "readonly",
  ReadableStream: "readonly",
  ReadableStreamBYOBReader: "readonly",
  ReadableStreamBYOBRequest: "readonly",
  ReadableStreamDefaultController: "readonly",
  ReadableStreamDefaultReader: "readonly",
  require: "readonly",
  Response: "readonly",
  setImmediate: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  structuredClone: "readonly",
  SubtleCrypto: "readonly",
  TextDecoder: "readonly",
  TextDecoderStream: "readonly",
  TextEncoder: "readonly",
  TextEncoderStream: "readonly",
  TransformStream: "readonly",
  TransformStreamDefaultController: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  WebAssembly: "readonly",
  WritableStream: "readonly",
  WritableStreamDefaultController: "readonly",
  WritableStreamDefaultWriter: "readonly",
};

// 微信小程序宿主环境全局变量
const wxGlobals = {
  wx: "readonly",
  App: "readonly",
  Page: "readonly",
  getApp: "readonly",
  getPage: "readonly",
  Component: "readonly",
  Behavior: "readonly",
  getCurrentPages: "readonly",
  requirePlugin: "readonly",
  window: "readonly",
  requestAnimationFrame: "readonly",
};

module.exports = [
  {
    ignores: ["node_modules/", "miniprogram_npm/", "dist/", "coverage/"],
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "script",
      globals: {
        ...nodeGlobals,
        ...wxGlobals,
      },
    },
    rules: {
      ...recommendedRules,
      "no-unused-vars": ["error", { args: "none", caughtErrors: "none" }],
      "no-console": ["error", { allow: ["error", "warn"] }],
      "no-debugger": "error",
      "no-empty": ["error", { allowEmptyCatch: true }],
      eqeqeq: ["warn", "always", { null: "ignore" }],
    },
  },
  {
    // 工程脚本（校验/部署）属 CLI 工具，需要直接向控制台输出结果
    files: ["scripts/**/*.js"],
    rules: {
      "no-console": "off",
    },
  },
  {
    // 单元测试运行于 Jest 环境（复刻 env.jest 提供的全局变量）
    files: ["__tests__/**/*.js"],
    languageOptions: {
      globals: {
        ...nodeGlobals,
        ...wxGlobals,
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        jest: "readonly",
      },
    },
  },
  {
    // 图片压缩工具为 Node ESM 脚本（构建期使用，不参与小程序打包）
    files: ["utils/compress-images.js"],
    languageOptions: {
      sourceType: "module",
    },
    rules: {
      "no-console": "off",
    },
  },
];
