锘?/ pages/article/detail/detail.js\n/**\n * 閺傚洨鐝风拠锔藉剰妞ょ敻娼?- 鐏炴洜銇氶弬鍥╃彿閸愬懎顔愰妴浣界槑鐠佸搫鍨悰銊ユ嫲娴滄帒濮╅崝鐔诲厴\n */\nimport { showToast } from '../../../utils/global';\n\nPage({\n  /**\n   * 妞ょ敻娼伴惃鍕灥婵鏆熼幑?
   */\n  data: {\n    articleId: 0, // 閺傚洨鐝稩D\n    article: {}, // 閺傚洨鐝风拠锔藉剰\n    loading: true, // 閸旂姾娴囬悩鑸碘偓?
    error: false, // 闁挎瑨顕ら悩鑸碘偓?
    likeCount: 0, // 閻愮绂愰弫浼村櫤\n    isLiked: false, // 閺勵垰鎯佸鑼仯鐠?
    commentList: [], // 鐠囧嫯顔戦崚妤勩€僜n    commentPage: 1, // 鐠囧嫯顔戣ぐ鎾冲妞ょ數鐖淺n    commentHasMore: true, // 鐠囧嫯顔戦弰顖氭儊閺堝娲挎径?
    commentContent: '', // 鐠囧嫯顔戦崘鍛啇\n    showCommentInput: false, // 閺勵垰鎯侀弰鍓с仛鐠囧嫯顔戞潏鎾冲弳濡?
    isFavorite: false, // 閺勵垰鎯佸鍙夋暪閽?
    favoriteCount: 0, // 閺€鎯版閺佷即鍣篭n    viewCount: 0, // 濞村繗顫嶉柌?
    replyToCommentId: null, // 閸ョ偛顦查惃鍕槑鐠佺瘨D\n    replyToUsername: '', // 閸ョ偛顦查惃鍕暏閹村嘲鎮昞n    loadingComments: false, // 鐠囧嫯顔戦崝鐘烘祰閻樿埖鈧?
    showSkeleton: true // 閺勵垰鎯侀弰鍓с仛妤犮劍鐏︾仦?
  },\n\n  /**\n   * 閻㈢喎鎳￠崨銊︽埂閸戣姤鏆?-閻╂垵鎯夋い鐢告桨閸旂姾娴嘰n   */\n  onLoad: function (options) {\n    if (options.id) {\n      this.setData({\n        articleId: parseInt(options.id)\n      });\n      this.getArticleDetail();\n      this.getCommentList();\n    } else {\n      this.setData({\n        loading: false,\n        showSkeleton: false,\n        error: true\n      });\n      wx.showToast({\n        title: '閺傚洨鐝稩D娑撳秴鐡ㄩ崷?,\n        icon: 'none'\n      });\n    }\n  },\n\n  /**\n   * 閻㈢喎鎳￠崨銊︽埂閸戣姤鏆?-閻╂垵鎯夋い鐢告桨閺勫墽銇歕n   */\n  onShow: function () {\n    // 閸欘垯浜掗崷銊ㄧ箹闁插苯鍩涢弬鐗堟瀮缁旂姵鏆熼幑顕嗙礉娓氬顩ч悙纭呯閵嗕焦鏁归挊蹇曞Ц閹?
  },\n\n  /**\n   * 閼惧嘲褰囬弬鍥╃彿鐠囷附鍎廫n   */\n  getArticleDetail: async function() {\n    const app = getApp();\n    try {\n      // 娴ｈ法鏁rticleService閼惧嘲褰囬弬鍥╃彿鐠囷附鍎廫n      const article = await app.services.article.getPostDetail(this.data.articleId);\n      \n      this.setData({\n        article: article,\n        likeCount: article.like_count || 0,\n        isLiked: article.is_liked || false,\n        isFavorite: article.is_favorite || false,\n        favoriteCount: article.favorite_count || 0,\n        viewCount: article.view_count || 0,\n        loading: false,\n        showSkeleton: false,\n        error: false\n      });\n      \n      // 鐠佸墽鐤嗘い鐢告桨閺嶅洭顣絓n      wx.setNavigationBarTitle({\n        title: article.title || '閺傚洨鐝风拠锔藉剰'\n      });\n      \n      // 鐠佹澘缍嶉弬鍥╃彿濞村繗顫嶆禍瀣╂\n      app.services.analytics.trackEvent('article_view', {\n        article_id: this.data.articleId,\n        article_title: article.title,\n        category_id: article.category_id\n      });\n    } catch (err) {\n      console.error('閼惧嘲褰囬弬鍥╃彿鐠囷附鍎忔径杈Е:', err);\n      showToast(err.message || '缂冩垹绮堕柨娆掝嚖閿涘本妫ゅ▔鏇炲鏉炶姤鏋冪粩?, 'none');\n      this.setData({\n        loading: false,\n        showSkeleton: false,\n        error: true\n      });\n    }\n  },\n\n  /**\n   * 閼惧嘲褰囩拠鍕啈閸掓銆僜n   */\n  getCommentList: async function() {\n    if (!this.data.commentHasMore) return;\n\n    const app = getApp();\n    try {\n      // 娴ｈ法鏁ommentService閼惧嘲褰囩拠鍕啈閸掓銆僜n      const res = await app.services.comment.getComments(this.data.articleId, {\n        page: this.data.commentPage,\n        per_page: 10\n      });\n      \n      const comments = res.comments || [];\n      const pages = res.pages || 1;\n      \n      // 婵″倹鐏夐弰顖滎儑娑撯偓妞ょ绱濋崚娆愭禌閹广垼鐦庣拋鍝勫灙鐞涱煉绱遍崥锕€鍨潻钘夊\n      if (this.data.commentPage === 1) {\n        this.setData({\n          commentList: comments\n        });\n      } else {\n        this.setData({\n          commentList: [...this.data.commentList, ...comments]\n        });\n      }\n      \n      // 閸掋倖鏌囬弰顖氭儊鏉╂ɑ婀侀弴鏉戭樋鐠囧嫯顔慭n      this.setData({\n        commentHasMore: this.data.commentPage < pages,\n        loadingComments: false\n      });\n    } catch (error) {\n      console.error('閼惧嘲褰囩拠鍕啈閸掓銆冩径杈Е:', error);\n      this.setData({\n        loadingComments: false\n      });\n      \n      if (this.data.commentPage === 1) {\n        showToast('鐠囧嫯顔戦崝鐘烘祰婢惰精瑙?, 'none');\n      }\n    }\n  },\n\n  /**\n   * 閻愮绂愰弬鍥╃彿\n   */\n  likeArticle: async function() {\n    const app = getApp();\n    // 濡偓閺屻儲妲搁崥锔炬瑜?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n\n    const isLike = !this.data.isLiked;\n    const successMsg = isLike ? '閻愮绂愰幋鎰' : '閸欐牗绉烽悙纭呯閹存劕濮?;\n    \n    try {\n      // 娑旀劘顫囬弴瀛樻煀UI\n      this.setData({\n        isLiked: isLike,\n        likeCount: isLike ? this.data.likeCount + 1 : Math.max(0, this.data.likeCount - 1)\n      });\n      \n      // 娴ｈ法鏁rticleService鏉╂稖顢戦悙纭呯閹垮秳缍擻n      await app.services.article.toggleLike(this.data.articleId);\n      \n      showToast(successMsg, 'success');\n      \n      // 鐠佹澘缍嶉悙纭呯娴滃娆n      app.services.analytics.trackEvent('article_like', {\n        article_id: this.data.articleId,\n        action: isLike ? 'like' : 'unlike'\n      });\n    } catch (error) {\n      // 婢惰精瑙﹂弮璺烘礀濠婃瓗I\n      this.setData({\n        isLiked: !isLike,\n        likeCount: isLike ? this.data.likeCount - 1 : this.data.likeCount + 1\n      });\n      showToast(error.message || '閹垮秳缍旀径杈Е', 'none');\n    }\n  },\n\n  /**\n   * 閺€鎯版閺傚洨鐝穃n   */\n  favoriteArticle: async function() {\n    const app = getApp();\n    // 濡偓閺屻儲妲搁崥锔炬瑜?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n\n    const isFavorite = !this.data.isFavorite;\n    const successMsg = isFavorite ? '閺€鎯版閹存劕濮? : '閸欐牗绉烽弨鎯版閹存劕濮?;\n    \n    try {\n      // 娑旀劘顫囬弴瀛樻煀UI\n      this.setData({\n        isFavorite: isFavorite,\n        favoriteCount: isFavorite ? this.data.favoriteCount + 1 : Math.max(0, this.data.favoriteCount - 1)\n      });\n      \n      // 娴ｈ法鏁rticleService鏉╂稖顢戦弨鎯版閹垮秳缍擻n      await app.services.article.toggleFavorite(this.data.articleId);\n      \n      showToast(successMsg, 'success');\n      \n      // 鐠佹澘缍嶉弨鎯版娴滃娆n      app.services.analytics.trackEvent('article_favorite', {\n        article_id: this.data.articleId,\n        action: isFavorite ? 'favorite' : 'unfavorite'\n      });\n    } catch (error) {\n      // 婢惰精瑙﹂弮璺烘礀濠婃瓗I\n      this.setData({\n        isFavorite: !isFavorite,\n        favoriteCount: isFavorite ? this.data.favoriteCount - 1 : this.data.favoriteCount + 1\n      });\n      showToast(error.message || '閹垮秳缍旀径杈Е', 'none');\n    }\n  },\n\n  /**\n   * 閹绘劒姘︾拠鍕啈\n   */\n  submitComment: async function() {\n    const content = this.data.commentContent.trim();\n    if (!content) {\n      showToast('鐠囧嫯顔戦崘鍛啇娑撳秷鍏樻稉铏光敄', 'none');\n      return;\n    }\n\n    const app = getApp();\n    const isReply = !!this.data.replyToCommentId;\n    \n    try {\n      // 娴ｈ法鏁ommentService閹绘劒姘︾拠鍕啈\n      const newComment = await app.services.comment.addComment(this.data.articleId, {\n        content: content,\n        parent_id: this.data.replyToCommentId || undefined\n      });\n      \n      // 闁插秶鐤嗛悩鑸碘偓?
      this.setData({\n        commentContent: '',\n        showCommentInput: false,\n        replyToCommentId: null,\n        replyToUsername: ''\n      });\n      \n      // 閺囧瓨鏌婄拠鍕啈閸掓銆僜n      if (isReply) {\n        // 閸ョ偛顦茬拠鍕啈閺冭泛鍩涢弬鐗堟殻娑擃亣鐦庣拋鍝勫灙鐞?
        this.setData({\n          commentPage: 1,\n          commentHasMore: true\n        });\n        this.getCommentList();\n      } else {\n        // 閺咁噣鈧俺鐦庣拋铏规纯閹恒儲鍧婇崝鐘插煂閸掓銆冨鈧径?
        this.setData({\n          commentList: [newComment, ...this.data.commentList]\n        });\n      }\n      \n      showToast('鐠囧嫯顔戦幋鎰', 'success');\n      \n      // 鐠佹澘缍嶇拠鍕啈娴滃娆n      app.services.analytics.trackEvent('article_comment', {\n        article_id: this.data.articleId,\n        comment_id: newComment.id,\n        is_reply: isReply\n      });\n    } catch (error) {\n      showToast(error.message || '鐠囧嫯顔戞径杈Е', 'none');\n    }\n  },\n\n  /**\n   * 鏉堟挸鍙嗙拠鍕啈閸愬懎顔怽n   */\n  onCommentInput: function(e) {\n    this.setData({\n      commentContent: e.detail.value\n    });\n  },\n\n  /**\n   * 閺勫墽銇氱拠鍕啈鏉堟挸鍙嗗?
   */\n  showCommentBox: function() {\n    const app = getApp();\n    // 濡偓閺屻儲妲搁崥锔炬瑜?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n\n    // 濞撳懘娅庨崶鐐差槻閻樿埖鈧緤绱濋弰鍓с仛閺咁噣鈧俺鐦庣拋鐑橆攱\n    this.setData({\n      replyToCommentId: null,\n      replyToUsername: '',\n      showCommentInput: true\n    });\n  },\n  \n  /**\n   * 閸旂姾娴囬弴鏉戭樋鐠囧嫯顔慭n   */\n  loadMoreComments: function() {\n    if (!this.data.commentHasMore || this.data.loadingComments) return;\n    \n    this.setData({\n      loadingComments: true,\n      commentPage: this.data.commentPage + 1\n    });\n    \n    this.getCommentList();\n  },\n\n  /**\n   * 闂呮劘妫岀拠鍕啈鏉堟挸鍙嗗?
   */\n  hideCommentBox: function() {\n    this.setData({\n      showCommentInput: false,\n      replyToCommentId: null,\n      replyToUsername: ''\n    });\n  },\n\n  /**\n   * 閻愮绂愮拠鍕啈\n   */\n  likeComment: async function(e) {\n    const commentId = e.currentTarget.dataset.id;\n    const app = getApp();\n    \n    // 濡偓閺屻儲妲搁崥锔炬瑜?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n    \n    // 閼惧嘲褰囪ぐ鎾冲鐠囧嫯顔戠€电钖勯崪宀€鍌ㄥ?
    const commentIndex = this.data.commentList.findIndex(item => item.id === commentId);\n    if (commentIndex === -1) return;\n    \n    const currentComment = this.data.commentList[commentIndex];\n    const newIsLiked = !currentComment.is_liked;\n    const newLikeCount = newIsLiked ? (currentComment.like_count || 0) + 1 : Math.max(0, (currentComment.like_count || 1) - 1);\n    \n    // 娑旀劘顫囬弴瀛樻煀UI\n    const newCommentList = [...this.data.commentList];\n    newCommentList[commentIndex] = {\n      ...newCommentList[commentIndex],\n      is_liked: newIsLiked,\n      like_count: newLikeCount\n    };\n    this.setData({\n      commentList: newCommentList\n    });\n    \n    try {\n      // 娴ｈ法鏁ommentService鏉╂稖顢戠拠鍕啈閻愮绂愰幙宥勭稊\n      await app.services.comment.toggleLike(commentId);\n      \n      // 鐠佹澘缍嶇拠鍕啈閻愮绂愭禍瀣╂\n      app.services.analytics.trackEvent('comment_like', {\n        comment_id: commentId,\n        action: newIsLiked ? 'like' : 'unlike'\n      });\n    } catch (error) {\n      // 鐠囬攱鐪版径杈Е閿涘苯娲栧姝嶪\n      newCommentList[commentIndex] = {\n        ...newCommentList[commentIndex],\n        is_liked: !newIsLiked,\n        like_count: currentComment.like_count || 0\n      };\n      this.setData({\n        commentList: newCommentList\n      });\n      showToast(error.message || '閹垮秳缍旀径杈Е', 'none');\n    }\n  },\n\n  /**\n   * 閸ョ偛顦茬拠鍕啈\n   */\n  replyToComment: function(e) {\n    const commentId = e.currentTarget.dataset.id;\n    const username = e.currentTarget.dataset.username;\n    const app = getApp();\n    \n    // 濡偓閺屻儲妲搁崥锔炬瑜?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n    \n    // 鐠佸墽鐤嗛崶鐐差槻閻樿埖鈧礁鑻熼弰鍓с仛鐠囧嫯顔戝?
    this.setData({\n      replyToCommentId: commentId,\n      replyToUsername: username,\n      showCommentInput: true,\n      commentContent: `@${username} `\n    });\n  },\n  \n  /**\n   * 閼惧嘲褰囩化鑽ょ埠娣団剝浼呴敍鍫㈡暏娴滃氦鐨熺拠鏇礆\n   * @private\n   */\n  _getSystemInfo: function() {\n    try {\n      return wx.getSystemInfoSync() || {};\n    } catch (e) {\n      console.error('閼惧嘲褰囩化鑽ょ埠娣団剝浼呮径杈Е:', e);\n      return {};\n    }\n  },\n\n  /**\n   * 閸掑棔闊╅弬鍥╃彿\n   */\n  onShareAppMessage: function() {\n    return {\n      title: this.data.article.title || '閸掑棔闊╅弬鍥╃彿',\n      path: '/pages/article/detail/detail?id=' + this.data.articleId,\n      imageUrl: this.data.article.thumbnail\n    };\n  },\n\n  /**\n   * 妞ょ敻娼版稉濠冨鐟欙箑绨虫禍瀣╂閻ㄥ嫬顦╅悶鍡楀毐閺?
   */\n  onReachBottom: function() {\n    if (this.data.commentHasMore) {\n      this.setData({\n        commentPage: this.data.commentPage + 1\n      });\n      this.getCommentList();\n    }\n  },\n\n  /**\n   * 妞ょ敻娼伴惄绋垮彠娴滃娆㈡径鍕倞閸戣姤鏆?-閻╂垵鎯夐悽銊﹀煕娑撳濯洪崝銊ょ稊\n   */\n  onPullDownRefresh: function() {\n    this.setData({\n      showSkeleton: true,\n      error: false\n    });\n    this.getArticleDetail();\n    this.setData({\n      commentPage: 1,\n      commentHasMore: true\n    });\n    this.getCommentList();\n    wx.stopPullDownRefresh();\n  },\n\n  /**\n   * 闁插秷鐦崝鐘烘祰閺佺増宓乗n   */\n  onRetry: function() {\n    this.setData({\n      loading: true,\n      showSkeleton: true,\n      error: false\n    });\n    this.getArticleDetail();\n    this.setData({\n      commentPage: 1,\n      commentHasMore: true\n    });\n    this.getCommentList();\n  },\n\n  /**\n   * 鐠哄疇娴嗛崚鎵祲閸忚櫕鏋冪粩鐘侯嚊閹?
   */\n  goToArticleDetail: function(e) {\n    const articleId = e.currentTarget.dataset.id;\n    if (!articleId) return;\n    \n    wx.navigateTo({\n      url: '/pages/article/detail/detail?id=' + articleId,\n      fail: function() {\n        showToast('鐠哄疇娴嗛弬鍥╃彿鐠囷附鍎忔径杈Е', 'none');\n      }\n    });\n  }\n});\n