// pages/article/detail/detail.js\n/**\n * 鏂囩珷璇︽儏椤甸潰 - 灞曠ず鏂囩珷鍐呭銆佽瘎璁哄垪琛ㄥ拰浜掑姩鍔熻兘\n */\nimport { showToast } from '../../../utils/global';\n\nPage({\n  /**\n   * 椤甸潰鐨勫垵濮嬫暟鎹?
   */\n  data: {\n    articleId: 0, // 鏂囩珷ID\n    article: {}, // 鏂囩珷璇︽儏\n    loading: true, // 鍔犺浇鐘舵€?
    error: false, // 閿欒鐘舵€?
    likeCount: 0, // 鐐硅禐鏁伴噺\n    isLiked: false, // 鏄惁宸茬偣璧?
    commentList: [], // 璇勮鍒楄〃\n    commentPage: 1, // 璇勮褰撳墠椤电爜\n    commentHasMore: true, // 璇勮鏄惁鏈夋洿澶?
    commentContent: '', // 璇勮鍐呭\n    showCommentInput: false, // 鏄惁鏄剧ず璇勮杈撳叆妗?
    isFavorite: false, // 鏄惁宸叉敹钘?
    favoriteCount: 0, // 鏀惰棌鏁伴噺\n    viewCount: 0, // 娴忚閲?
    replyToCommentId: null, // 鍥炲鐨勮瘎璁篒D\n    replyToUsername: '', // 鍥炲鐨勭敤鎴峰悕\n    loadingComments: false, // 璇勮鍔犺浇鐘舵€?
    showSkeleton: true // 鏄惁鏄剧ず楠ㄦ灦灞?
  },\n\n  /**\n   * 鐢熷懡鍛ㄦ湡鍑芥暟--鐩戝惉椤甸潰鍔犺浇\n   */\n  onLoad: function (options) {\n    if (options.id) {\n      this.setData({\n        articleId: parseInt(options.id)\n      });\n      this.getArticleDetail();\n      this.getCommentList();\n    } else {\n      this.setData({\n        loading: false,\n        showSkeleton: false,\n        error: true\n      });\n      wx.showToast({\n        title: '鏂囩珷ID涓嶅瓨鍦?,\n        icon: 'none'\n      });\n    }\n  },\n\n  /**\n   * 鐢熷懡鍛ㄦ湡鍑芥暟--鐩戝惉椤甸潰鏄剧ず\n   */\n  onShow: function () {\n    // 鍙互鍦ㄨ繖閲屽埛鏂版枃绔犳暟鎹紝渚嬪鐐硅禐銆佹敹钘忕姸鎬?
  },\n\n  /**\n   * 鑾峰彇鏂囩珷璇︽儏\n   */\n  getArticleDetail: async function() {\n    const app = getApp();\n    try {\n      // 浣跨敤articleService鑾峰彇鏂囩珷璇︽儏\n      const article = await app.services.article.getPostDetail(this.data.articleId);\n      \n      this.setData({\n        article: article,\n        likeCount: article.like_count || 0,\n        isLiked: article.is_liked || false,\n        isFavorite: article.is_favorite || false,\n        favoriteCount: article.favorite_count || 0,\n        viewCount: article.view_count || 0,\n        loading: false,\n        showSkeleton: false,\n        error: false\n      });\n      \n      // 璁剧疆椤甸潰鏍囬\n      wx.setNavigationBarTitle({\n        title: article.title || '鏂囩珷璇︽儏'\n      });\n      \n      // 璁板綍鏂囩珷娴忚浜嬩欢\n      app.services.analytics.trackEvent('article_view', {\n        article_id: this.data.articleId,\n        article_title: article.title,\n        category_id: article.category_id\n      });\n    } catch (err) {\n      console.error('鑾峰彇鏂囩珷璇︽儏澶辫触:', err);\n      showToast(err.message || '缃戠粶閿欒锛屾棤娉曞姞杞芥枃绔?, 'none');\n      this.setData({\n        loading: false,\n        showSkeleton: false,\n        error: true\n      });\n    }\n  },\n\n  /**\n   * 鑾峰彇璇勮鍒楄〃\n   */\n  getCommentList: async function() {\n    if (!this.data.commentHasMore) return;\n\n    const app = getApp();\n    try {\n      // 浣跨敤commentService鑾峰彇璇勮鍒楄〃\n      const res = await app.services.comment.getComments(this.data.articleId, {\n        page: this.data.commentPage,\n        per_page: 10\n      });\n      \n      const comments = res.comments || [];\n      const pages = res.pages || 1;\n      \n      // 濡傛灉鏄涓€椤碉紝鍒欐浛鎹㈣瘎璁哄垪琛紱鍚﹀垯杩藉姞\n      if (this.data.commentPage === 1) {\n        this.setData({\n          commentList: comments\n        });\n      } else {\n        this.setData({\n          commentList: [...this.data.commentList, ...comments]\n        });\n      }\n      \n      // 鍒ゆ柇鏄惁杩樻湁鏇村璇勮\n      this.setData({\n        commentHasMore: this.data.commentPage < pages,\n        loadingComments: false\n      });\n    } catch (error) {\n      console.error('鑾峰彇璇勮鍒楄〃澶辫触:', error);\n      this.setData({\n        loadingComments: false\n      });\n      \n      if (this.data.commentPage === 1) {\n        showToast('璇勮鍔犺浇澶辫触', 'none');\n      }\n    }\n  },\n\n  /**\n   * 鐐硅禐鏂囩珷\n   */\n  likeArticle: async function() {\n    const app = getApp();\n    // 妫€鏌ユ槸鍚︾櫥褰?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n\n    const isLike = !this.data.isLiked;\n    const successMsg = isLike ? '鐐硅禐鎴愬姛' : '鍙栨秷鐐硅禐鎴愬姛';\n    \n    try {\n      // 涔愯鏇存柊UI\n      this.setData({\n        isLiked: isLike,\n        likeCount: isLike ? this.data.likeCount + 1 : Math.max(0, this.data.likeCount - 1)\n      });\n      \n      // 浣跨敤articleService杩涜鐐硅禐鎿嶄綔\n      await app.services.article.toggleLike(this.data.articleId);\n      \n      showToast(successMsg, 'success');\n      \n      // 璁板綍鐐硅禐浜嬩欢\n      app.services.analytics.trackEvent('article_like', {\n        article_id: this.data.articleId,\n        action: isLike ? 'like' : 'unlike'\n      });\n    } catch (error) {\n      // 澶辫触鏃跺洖婊歎I\n      this.setData({\n        isLiked: !isLike,\n        likeCount: isLike ? this.data.likeCount - 1 : this.data.likeCount + 1\n      });\n      showToast(error.message || '鎿嶄綔澶辫触', 'none');\n    }\n  },\n\n  /**\n   * 鏀惰棌鏂囩珷\n   */\n  favoriteArticle: async function() {\n    const app = getApp();\n    // 妫€鏌ユ槸鍚︾櫥褰?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n\n    const isFavorite = !this.data.isFavorite;\n    const successMsg = isFavorite ? '鏀惰棌鎴愬姛' : '鍙栨秷鏀惰棌鎴愬姛';\n    \n    try {\n      // 涔愯鏇存柊UI\n      this.setData({\n        isFavorite: isFavorite,\n        favoriteCount: isFavorite ? this.data.favoriteCount + 1 : Math.max(0, this.data.favoriteCount - 1)\n      });\n      \n      // 浣跨敤articleService杩涜鏀惰棌鎿嶄綔\n      await app.services.article.toggleFavorite(this.data.articleId);\n      \n      showToast(successMsg, 'success');\n      \n      // 璁板綍鏀惰棌浜嬩欢\n      app.services.analytics.trackEvent('article_favorite', {\n        article_id: this.data.articleId,\n        action: isFavorite ? 'favorite' : 'unfavorite'\n      });\n    } catch (error) {\n      // 澶辫触鏃跺洖婊歎I\n      this.setData({\n        isFavorite: !isFavorite,\n        favoriteCount: isFavorite ? this.data.favoriteCount - 1 : this.data.favoriteCount + 1\n      });\n      showToast(error.message || '鎿嶄綔澶辫触', 'none');\n    }\n  },\n\n  /**\n   * 鎻愪氦璇勮\n   */\n  submitComment: async function() {\n    const content = this.data.commentContent.trim();\n    if (!content) {\n      showToast('璇勮鍐呭涓嶈兘涓虹┖', 'none');\n      return;\n    }\n\n    const app = getApp();\n    const isReply = !!this.data.replyToCommentId;\n    \n    try {\n      // 浣跨敤commentService鎻愪氦璇勮\n      const newComment = await app.services.comment.addComment(this.data.articleId, {\n        content: content,\n        parent_id: this.data.replyToCommentId || undefined\n      });\n      \n      // 閲嶇疆鐘舵€?
      this.setData({\n        commentContent: '',\n        showCommentInput: false,\n        replyToCommentId: null,\n        replyToUsername: ''\n      });\n      \n      // 鏇存柊璇勮鍒楄〃\n      if (isReply) {\n        // 鍥炲璇勮鏃跺埛鏂版暣涓瘎璁哄垪琛?
        this.setData({\n          commentPage: 1,\n          commentHasMore: true\n        });\n        this.getCommentList();\n      } else {\n        // 鏅€氳瘎璁虹洿鎺ユ坊鍔犲埌鍒楄〃寮€澶?
        this.setData({\n          commentList: [newComment, ...this.data.commentList]\n        });\n      }\n      \n      showToast('璇勮鎴愬姛', 'success');\n      \n      // 璁板綍璇勮浜嬩欢\n      app.services.analytics.trackEvent('article_comment', {\n        article_id: this.data.articleId,\n        comment_id: newComment.id,\n        is_reply: isReply\n      });\n    } catch (error) {\n      showToast(error.message || '璇勮澶辫触', 'none');\n    }\n  },\n\n  /**\n   * 杈撳叆璇勮鍐呭\n   */\n  onCommentInput: function(e) {\n    this.setData({\n      commentContent: e.detail.value\n    });\n  },\n\n  /**\n   * 鏄剧ず璇勮杈撳叆妗?
   */\n  showCommentBox: function() {\n    const app = getApp();\n    // 妫€鏌ユ槸鍚︾櫥褰?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n\n    // 娓呴櫎鍥炲鐘舵€侊紝鏄剧ず鏅€氳瘎璁烘\n    this.setData({\n      replyToCommentId: null,\n      replyToUsername: '',\n      showCommentInput: true\n    });\n  },\n  \n  /**\n   * 鍔犺浇鏇村璇勮\n   */\n  loadMoreComments: function() {\n    if (!this.data.commentHasMore || this.data.loadingComments) return;\n    \n    this.setData({\n      loadingComments: true,\n      commentPage: this.data.commentPage + 1\n    });\n    \n    this.getCommentList();\n  },\n\n  /**\n   * 闅愯棌璇勮杈撳叆妗?
   */\n  hideCommentBox: function() {\n    this.setData({\n      showCommentInput: false,\n      replyToCommentId: null,\n      replyToUsername: ''\n    });\n  },\n\n  /**\n   * 鐐硅禐璇勮\n   */\n  likeComment: async function(e) {\n    const commentId = e.currentTarget.dataset.id;\n    const app = getApp();\n    \n    // 妫€鏌ユ槸鍚︾櫥褰?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n    \n    // 鑾峰彇褰撳墠璇勮瀵硅薄鍜岀储寮?
    const commentIndex = this.data.commentList.findIndex(item => item.id === commentId);\n    if (commentIndex === -1) return;\n    \n    const currentComment = this.data.commentList[commentIndex];\n    const newIsLiked = !currentComment.is_liked;\n    const newLikeCount = newIsLiked ? (currentComment.like_count || 0) + 1 : Math.max(0, (currentComment.like_count || 1) - 1);\n    \n    // 涔愯鏇存柊UI\n    const newCommentList = [...this.data.commentList];\n    newCommentList[commentIndex] = {\n      ...newCommentList[commentIndex],\n      is_liked: newIsLiked,\n      like_count: newLikeCount\n    };\n    this.setData({\n      commentList: newCommentList\n    });\n    \n    try {\n      // 浣跨敤commentService杩涜璇勮鐐硅禐鎿嶄綔\n      await app.services.comment.toggleLike(commentId);\n      \n      // 璁板綍璇勮鐐硅禐浜嬩欢\n      app.services.analytics.trackEvent('comment_like', {\n        comment_id: commentId,\n        action: newIsLiked ? 'like' : 'unlike'\n      });\n    } catch (error) {\n      // 璇锋眰澶辫触锛屽洖婊歎I\n      newCommentList[commentIndex] = {\n        ...newCommentList[commentIndex],\n        is_liked: !newIsLiked,\n        like_count: currentComment.like_count || 0\n      };\n      this.setData({\n        commentList: newCommentList\n      });\n      showToast(error.message || '鎿嶄綔澶辫触', 'none');\n    }\n  },\n\n  /**\n   * 鍥炲璇勮\n   */\n  replyToComment: function(e) {\n    const commentId = e.currentTarget.dataset.id;\n    const username = e.currentTarget.dataset.username;\n    const app = getApp();\n    \n    // 妫€鏌ユ槸鍚︾櫥褰?
    if (!app.isLoggedIn()) {\n      wx.navigateTo({\n        url: '/pages/user/login/login'\n      });\n      return;\n    }\n    \n    // 璁剧疆鍥炲鐘舵€佸苟鏄剧ず璇勮妗?
    this.setData({\n      replyToCommentId: commentId,\n      replyToUsername: username,\n      showCommentInput: true,\n      commentContent: `@${username} `\n    });\n  },\n  \n  /**\n   * 鑾峰彇绯荤粺淇℃伅锛堢敤浜庤皟璇曪級\n   * @private\n   */\n  _getSystemInfo: function() {\n    try {\n      return wx.getSystemInfoSync() || {};\n    } catch (e) {\n      console.error('鑾峰彇绯荤粺淇℃伅澶辫触:', e);\n      return {};\n    }\n  },\n\n  /**\n   * 鍒嗕韩鏂囩珷\n   */\n  onShareAppMessage: function() {\n    return {\n      title: this.data.article.title || '鍒嗕韩鏂囩珷',\n      path: '/pages/article/detail/detail?id=' + this.data.articleId,\n      imageUrl: this.data.article.thumbnail\n    };\n  },\n\n  /**\n   * 椤甸潰涓婃媺瑙﹀簳浜嬩欢鐨勫鐞嗗嚱鏁?
   */\n  onReachBottom: function() {\n    if (this.data.commentHasMore) {\n      this.setData({\n        commentPage: this.data.commentPage + 1\n      });\n      this.getCommentList();\n    }\n  },\n\n  /**\n   * 椤甸潰鐩稿叧浜嬩欢澶勭悊鍑芥暟--鐩戝惉鐢ㄦ埛涓嬫媺鍔ㄤ綔\n   */\n  onPullDownRefresh: function() {\n    this.setData({\n      showSkeleton: true,\n      error: false\n    });\n    this.getArticleDetail();\n    this.setData({\n      commentPage: 1,\n      commentHasMore: true\n    });\n    this.getCommentList();\n    wx.stopPullDownRefresh();\n  },\n\n  /**\n   * 閲嶈瘯鍔犺浇鏁版嵁\n   */\n  onRetry: function() {\n    this.setData({\n      loading: true,\n      showSkeleton: true,\n      error: false\n    });\n    this.getArticleDetail();\n    this.setData({\n      commentPage: 1,\n      commentHasMore: true\n    });\n    this.getCommentList();\n  },\n\n  /**\n   * 璺宠浆鍒扮浉鍏虫枃绔犺鎯?
   */\n  goToArticleDetail: function(e) {\n    const articleId = e.currentTarget.dataset.id;\n    if (!articleId) return;\n    \n    wx.navigateTo({\n      url: '/pages/article/detail/detail?id=' + articleId,\n      fail: function() {\n        showToast('璺宠浆鏂囩珷璇︽儏澶辫触', 'none');\n      }\n    });\n  }\n});