/**\n * 鏂囦欢鍚? socialService.test.js\n * 鐗堟湰鍙? 1.0.0\n * 鏇存柊鏃ユ湡: 2025-11-30\n * 浣滆€? Sut\n * 鎻忚堪: 绀句氦鏈嶅姟鍗曞厓娴嬭瘯\n */\n\n// 妯℃嫙渚濊禆妯″潡\njest.mock('../../utils/request', () => ({\n  post: jest.fn(),\n  get: jest.fn(),\n  put: jest.fn(),\n  delete: jest.fn()\n}));\n\n// 妯℃嫙寰俊API\njest.mock('wx', () => ({\n  showToast: jest.fn()\n}));\n\nconst request = require('../../utils/request');\nconst wx = require('wx');\nconst socialService = require('../../services/socialService');\n\ndescribe('socialService', () => {\n  beforeEach(() => {\n    // 娓呴櫎鎵€鏈夋ā鎷熻皟鐢?
    jest.clearAllMocks();\n  });\n\n  describe('shareProduct', () => {\n    it('should share product successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockOptions = {\n        productId: '1',\n        title: '娴嬭瘯鍟嗗搧',\n        description: '娴嬭瘯鍟嗗搧鎻忚堪',\n        imageUrl: 'https://example.com/image.jpg',\n        shareChannel: 'wechat'\n      };\n      const mockResponse = { success: true, shareId: 'share_123' };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.post.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.shareProduct(mockOptions);\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockResponse);\n      expect(request.post).toHaveBeenCalledWith('/social/share/product', mockOptions);\n    });\n\n    it('should use default shareChannel if not provided', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockOptions = {\n        productId: '1',\n        title: '娴嬭瘯鍟嗗搧'\n      };\n      const mockResponse = { success: true, shareId: 'share_123' };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.post.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      await socialService.shareProduct(mockOptions);\n      \n      // 楠岃瘉缁撴灉\n      expect(request.post).toHaveBeenCalledWith('/social/share/product', {\n        ...mockOptions,\n        shareChannel: 'wechat',\n        description: undefined,\n        imageUrl: undefined\n      });\n    });\n\n    it('should throw error if productId is not provided', async () => {\n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.shareProduct({})).rejects.toThrow('鍟嗗搧ID涓嶈兘涓虹┖');\n      expect(request.post).not.toHaveBeenCalled();\n    });\n  });\n\n  describe('getShareRecords', () => {\n    it('should get share records successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockRecords = [\n        { id: 'share_1', productId: '1', shareChannel: 'wechat', createdAt: '2025-11-30' },\n        { id: 'share_2', productId: '2', shareChannel: 'friend', createdAt: '2025-11-29' }\n      ];\n      const mockResponse = { data: mockRecords, total: 2, page: 1, pageSize: 20 };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.get.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.getShareRecords();\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockResponse);\n      expect(request.get).toHaveBeenCalledWith('/social/share/records', {\n        page: 1,\n        pageSize: 20,\n        sort: 'newest'\n      });\n    });\n\n    it('should use custom options when provided', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockOptions = {\n        page: 2,\n        pageSize: 10,\n        sort: 'oldest'\n      };\n      const mockResponse = { data: [], total: 0, page: 2, pageSize: 10 };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.get.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      await socialService.getShareRecords(mockOptions);\n      \n      // 楠岃瘉缁撴灉\n      expect(request.get).toHaveBeenCalledWith('/social/share/records', mockOptions);\n    });\n  });\n\n  describe('getShareStats', () => {\n    it('should get user share stats successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockStats = { totalShares: 10, totalProducts: 5, topChannels: ['wechat', 'friend'] };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.get.mockResolvedValue(mockStats);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.getShareStats();\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockStats);\n      expect(request.get).toHaveBeenCalledWith('/social/share/stats');\n    });\n\n    it('should get product share stats successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const productId = '1';\n      const mockStats = { totalShares: 5, shareChannels: ['wechat', 'circle'] };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.get.mockResolvedValue(mockStats);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.getShareStats(productId);\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockStats);\n      expect(request.get).toHaveBeenCalledWith(`/social/share/stats/product/${productId}`);\n    });\n  });\n\n  describe('getProductComments', () => {\n    it('should get product comments successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const productId = '1';\n      const mockComments = [\n        { id: 'comment_1', content: '娴嬭瘯璇勮1', rating: 5, createdAt: '2025-11-30' },\n        { id: 'comment_2', content: '娴嬭瘯璇勮2', rating: 4, createdAt: '2025-11-29' }\n      ];\n      const mockResponse = { data: mockComments, total: 2, page: 1, pageSize: 20 };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.get.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.getProductComments({ productId });\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockResponse);\n      expect(request.get).toHaveBeenCalledWith(`/products/${productId}/comments`, {\n        page: 1,\n        pageSize: 20,\n        sort: 'newest'\n      });\n    });\n\n    it('should throw error if productId is not provided', async () => {\n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.getProductComments({})).rejects.toThrow('鍟嗗搧ID涓嶈兘涓虹┖');\n      expect(request.get).not.toHaveBeenCalled();\n    });\n\n    it('should use custom options when provided', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockOptions = {\n        productId: '1',\n        page: 2,\n        pageSize: 10,\n        sort: 'highest',\n        minRating: 4,\n        withImages: true\n      };\n      const mockResponse = { data: [], total: 0, page: 2, pageSize: 10 };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.get.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      await socialService.getProductComments(mockOptions);\n      \n      // 楠岃瘉缁撴灉\n      expect(request.get).toHaveBeenCalledWith(`/products/${mockOptions.productId}/comments`, {\n        page: mockOptions.page,\n        pageSize: mockOptions.pageSize,\n        sort: mockOptions.sort,\n        minRating: mockOptions.minRating,\n        withImages: mockOptions.withImages\n      });\n    });\n  });\n\n  describe('addProductComment', () => {\n    it('should add product comment successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockCommentData = {\n        productId: '1',\n        content: '娴嬭瘯璇勮鍐呭',\n        rating: 5,\n        anonymous: false,\n        images: []\n      };\n      const mockResponse = { id: 'comment_1', ...mockCommentData, createdAt: '2025-11-30' };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.post.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.addProductComment(mockCommentData);\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockResponse);\n      expect(request.post).toHaveBeenCalledWith('/social/comments/product', mockCommentData);\n    });\n\n    it('should throw error if productId is not provided', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockCommentData = {\n        content: '娴嬭瘯璇勮鍐呭',\n        rating: 5\n      };\n      \n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.addProductComment(mockCommentData)).rejects.toThrow('鍟嗗搧ID涓嶈兘涓虹┖');\n      expect(request.post).not.toHaveBeenCalled();\n    });\n\n    it('should throw error if content is empty', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockCommentData = {\n        productId: '1',\n        content: '',\n        rating: 5\n      };\n      \n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.addProductComment(mockCommentData)).rejects.toThrow('璇勮鍐呭涓嶈兘涓虹┖');\n      expect(request.post).not.toHaveBeenCalled();\n    });\n\n    it('should throw error if rating is invalid', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockCommentData = {\n        productId: '1',\n        content: '娴嬭瘯璇勮鍐呭',\n        rating: 6 // 瓒呭嚭鑼冨洿1-5\n      };\n      \n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.addProductComment(mockCommentData)).rejects.toThrow('璇勫垎蹇呴』鍦?-5涔嬮棿');\n      expect(request.post).not.toHaveBeenCalled();\n    });\n  });\n\n  describe('likeProduct', () => {\n    it('should like product successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const productId = '1';\n      const mockResponse = { success: true, likeId: 'like_123' };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.post.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.likeProduct(productId);\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockResponse);\n      expect(request.post).toHaveBeenCalledWith(`/social/like/product/${productId}`);\n    });\n\n    it('should throw error if productId is not provided', async () => {\n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.likeProduct()).rejects.toThrow('鍟嗗搧ID涓嶈兘涓虹┖');\n      expect(request.post).not.toHaveBeenCalled();\n    });\n  });\n\n  describe('unlikeProduct', () => {\n    it('should unlike product successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const productId = '1';\n      const mockResponse = { success: true };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.delete.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.unlikeProduct(productId);\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockResponse);\n      expect(request.delete).toHaveBeenCalledWith(`/social/like/product/${productId}`);\n    });\n\n    it('should throw error if productId is not provided', async () => {\n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.unlikeProduct()).rejects.toThrow('鍟嗗搧ID涓嶈兘涓虹┖');\n      expect(request.delete).not.toHaveBeenCalled();\n    });\n  });\n\n  describe('checkLikeStatus', () => {\n    it('should check like status successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const mockOptions = {\n        targetId: '1',\n        targetType: 'product'\n      };\n      const mockResponse = { isLiked: true, likeId: 'like_123' };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.get.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.checkLikeStatus(mockOptions);\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockResponse);\n      expect(request.get).toHaveBeenCalledWith('/social/like/check', mockOptions);\n    });\n\n    it('should throw error if targetId is not provided', async () => {\n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.checkLikeStatus({ targetType: 'product' })).rejects.toThrow('鐩爣ID鍜岀被鍨嬩笉鑳戒负绌?);\n      expect(request.get).not.toHaveBeenCalled();\n    });\n\n    it('should throw error if targetType is not provided', async () => {\n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.checkLikeStatus({ targetId: '1' })).rejects.toThrow('鐩爣ID鍜岀被鍨嬩笉鑳戒负绌?);\n      expect(request.get).not.toHaveBeenCalled();\n    });\n  });\n\n  describe('likeComment', () => {\n    it('should like comment successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const commentId = '1';\n      const mockResponse = { success: true, likeId: 'like_123' };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.post.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.likeComment(commentId);\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockResponse);\n      expect(request.post).toHaveBeenCalledWith(`/social/comments/${commentId}/like`);\n    });\n\n    it('should throw error if commentId is not provided', async () => {\n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.likeComment()).rejects.toThrow('璇勮ID涓嶈兘涓虹┖');\n      expect(request.post).not.toHaveBeenCalled();\n    });\n  });\n\n  describe('unlikeComment', () => {\n    it('should unlike comment successfully', async () => {\n      // 鍑嗗娴嬭瘯鏁版嵁\n      const commentId = '1';\n      const mockResponse = { success: true };\n      \n      // 璁剧疆妯℃嫙杩斿洖鍊?
      request.delete.mockResolvedValue(mockResponse);\n      \n      // 鎵ц娴嬭瘯\n      const result = await socialService.unlikeComment(commentId);\n      \n      // 楠岃瘉缁撴灉\n      expect(result).toEqual(mockResponse);\n      expect(request.delete).toHaveBeenCalledWith(`/social/comments/${commentId}/like`);\n    });\n\n    it('should throw error if commentId is not provided', async () => {\n      // 鎵ц娴嬭瘯骞堕獙璇佺粨鏋?
      await expect(socialService.unlikeComment()).rejects.toThrow('璇勮ID涓嶈兘涓虹┖');\n      expect(request.delete).not.toHaveBeenCalled();\n    });\n  });\n});\n